"""Render step — downloads assets, renders video with Remotion, uploads to Drive.

Reads: Images + Scripts from Airtable, render_config from audio_sync, assets from Drive
Writes: Final MP4 to Drive, Final Video URL to Ideas table
Advances: Ready To Render → Rendered
Clients: google, airtable, slack, image_client (for regeneration)
"""

import asyncio
import json
import os
import re
import shutil
import subprocess
import time as _time
from pathlib import Path

from pipeline_constants import Statuses, IdeaFields, ImageFields, ScriptFields


def _clean_render_assets(label: str = "stale") -> int:
    """Remove all render assets from disk (public/, captions/, out/).

    Called before each render (to start fresh) and after upload
    (to free disk space).  Returns the number of files removed.
    """
    import glob as glob_mod

    remotion_dir = Path(__file__).parent.parent.parent.parent / "remotion-video"
    public_dir = remotion_dir / "public"
    captions_dir = remotion_dir / "src" / "captions"
    out_dir = remotion_dir / "out"

    to_remove: list[str] = []

    if public_dir.exists():
        to_remove += glob_mod.glob(str(public_dir / "Scene *.mp3"))
        to_remove += glob_mod.glob(str(public_dir / "Scene_*.png"))
        to_remove += glob_mod.glob(str(public_dir / "Scene_*.mp4"))
        to_remove += glob_mod.glob(str(public_dir / "render_config.json"))
        to_remove += glob_mod.glob(str(public_dir / "props.json"))
        to_remove += glob_mod.glob(str(public_dir / "sfx" / "*.mp3"))

    if captions_dir.exists():
        to_remove += glob_mod.glob(str(captions_dir / "Scene *.json"))

    if out_dir.exists():
        to_remove += glob_mod.glob(str(out_dir / "*.mp4"))

    # Also remove props.json at remotion root
    props_file = remotion_dir / "props.json"
    if props_file.exists():
        to_remove.append(str(props_file))

    removed = 0
    for f in to_remove:
        try:
            os.remove(f)
            removed += 1
        except OSError:
            pass

    if removed:
        print(f"  🧹 Cleaned {removed} {label} assets from disk")

    return removed


async def run(pipeline) -> dict:
    """Render video with Remotion and upload to Google Drive."""
    if not pipeline.current_idea:
        idea = pipeline.get_idea_by_status(Statuses.READY_TO_RENDER)
        if not idea:
            return {"error": "No idea with status 'Ready To Render'"}
        pipeline._load_idea(idea)

    print(f"\n🎬 RENDER BOT: Processing '{pipeline.video_title}'")
    pipeline.slack.notify(
        f"🎬 *Render starting:* _{pipeline.video_title}_\n"
        f"Running pre-flight checks, downloading assets, then rendering (concurrency=1, ~60-90 min)..."
    )

    # CLEAN ALL RENDER ASSETS — start fresh every render
    remotion_dir = Path(__file__).parent.parent.parent.parent / "remotion-video"
    public_dir = remotion_dir / "public"
    _clean_render_assets(label="pre-render")

    # PRE-FLIGHT CHECK: Regenerate any missing/pending images before render
    print(f"\n  🔍 Pre-flight check: Looking for missing images...")
    all_images = pipeline.airtable.get_all_images_for_video(pipeline.video_title)
    pending_images = [img for img in all_images if img.get(ImageFields.STATUS) == ImageFields.STATUS_PENDING]
    missing_images = [img for img in all_images if not img.get(ImageFields.IMAGE)]

    if pending_images or missing_images:
        count = len(pending_images) + len(missing_images)
        print(f"  ⚠️ Found {count} images needing regeneration!")
        regen_result = await pipeline.regenerate_images()
        if regen_result.get("regenerated", 0) > 0:
            print(f"  ✅ Regenerated {regen_result['regenerated']} images before render")
        else:
            print(f"  ❌ Failed to regenerate images - render may fail!")
    else:
        print(f"  ✅ All {len(all_images)} images present - ready to render")

    # Find Drive folder with assets
    asset_folders = _find_asset_folders(pipeline)

    print(f"  📂 Found {len(asset_folders)} Drive folders with assets:")
    for fid, desc in asset_folders:
        print(f"    📁 {desc}")

    # Export props
    props = await pipeline.package_for_remotion()

    props_file = remotion_dir / "props.json"
    public_dir.mkdir(exist_ok=True)

    with open(props_file, "w") as f:
        json.dump(props, f, indent=2)
    print(f"  📦 Props saved to: {props_file}")

    # Use the Whisper-based render_config.json generated by audio_sync
    pipeline_dir = Path(__file__).parent.parent
    video_id = pipeline.current_idea_id or "unknown"
    audio_sync_config = pipeline_dir / "timing" / video_id / "render_config.json"
    rc_path = public_dir / "render_config.json"

    if audio_sync_config.exists():
        shutil.copy2(audio_sync_config, rc_path)
        rc_data = json.loads(rc_path.read_text())
        rc_scene_count = len(rc_data.get("scenes", []))
        rc_total = rc_data.get("total_duration_seconds", 0)
        print(f"  📋 render_config.json (from audio_sync): "
              f"{rc_scene_count} images, {rc_total:.1f}s total")

        props["renderConfig"] = rc_data
        with open(props_file, "w") as f:
            json.dump(props, f, indent=2)
        print(f"  📦 Props updated with embedded renderConfig")
    else:
        raise RuntimeError(
            f"render_config.json not found at {audio_sync_config}. "
            f"Audio sync must run before rendering. "
            f"Re-run the pipeline from the image prompts stage."
        )

    # Download assets from Drive
    download_result = await _download_assets(pipeline, asset_folders, public_dir)
    download_ok = download_result["ok"]
    download_fail = download_result["fail"]
    audio_count = download_result["audio"]
    image_count = download_result["images"]
    video_clip_count = download_result["clips"]
    failed_assets = download_result["failed_assets"]
    total_assets = download_result["total"]

    # Final download summary
    if total_assets > 0:
        pipeline.slack.notify(
            f"⬇️ *Downloads complete:* _{pipeline.video_title}_\n"
            f"`██████████` *100%* — {download_ok}/{total_assets} files "
            f"({audio_count} audio, {image_count} images, {video_clip_count} clips)"
            + (f"\n⚠️ {download_fail} failed" if download_fail > 0 else "")
        )

    # Validate downloads
    print(f"  📊 Downloads: {download_ok} OK, {download_fail} failed")
    if download_fail > 0:
        fail_list = "\n".join(f"  • {a}" for a in failed_assets[:10])
        extra = f"\n  ... and {len(failed_assets) - 10} more" if len(failed_assets) > 10 else ""
        print(f"  ❌ Failed assets:\n{fail_list}{extra}")

    if download_ok == 0:
        pipeline.slack.notify(
            f"❌ *Render ABORTED:* _{pipeline.video_title}_\n"
            f"No Scene assets found across {len(asset_folders)} Drive folder(s).\n"
            f"Make sure Scene *.mp3 and Scene_*.png files exist in Google Drive."
        )
        return {"error": "No assets in Drive folders", "bot": "Render Bot"}

    if download_fail > download_ok * 0.3:
        fail_list = "\n".join(f"  • {a}" for a in failed_assets[:10])
        extra = f"\n  ... and {len(failed_assets) - 10} more" if len(failed_assets) > 10 else ""
        pipeline.slack.notify(
            f"❌ *Render ABORTED:* _{pipeline.video_title}_\n"
            f"Too many asset downloads failed ({download_fail} of {download_ok + download_fail}).\n"
            f"Failed:\n{fail_list}{extra}"
        )
        return {"error": f"{download_fail} asset downloads failed", "bot": "Render Bot"}

    print(f"  ✅ Assets downloaded: {audio_count} audio, {image_count} images, {video_clip_count} video clips")

    # Patch render_config with video clip data
    _patch_render_config_video_clips(props, public_dir)

    # Download SFX files
    sfx_count, sfx_total = await _download_sfx(pipeline, asset_folders, props, public_dir)

    # Select and download background music
    music_beds = await _select_and_download_music(pipeline, props, public_dir)
    if music_beds:
        props["renderConfig"]["music_beds"] = music_beds
        print(f"  🎵 Music beds: {len(music_beds)} tracks selected")

    # Re-save props.json after SFX and music processing
    with open(props_file, "w") as f:
        json.dump(props, f, indent=2)

    # Verify audio files
    missing_audio = await _verify_and_fetch_audio(pipeline, props, public_dir)
    if missing_audio:
        missing_list = ", ".join(missing_audio[:10])
        print(f"  ❌ Missing audio files: {missing_list}")
        pipeline.slack.notify(
            f"❌ *Render ABORTED:* _{pipeline.video_title}_\n"
            f"Missing audio: {missing_list}\n"
            f"Searched Drive + Airtable — these files were not found anywhere."
        )
        return {"error": f"Missing audio: {missing_list}", "bot": "Render Bot"}

    # Notify assets ready
    scene_count = len(props.get("scenes", []))
    rc_scenes = props.get("renderConfig", {}).get("scenes", [])
    actual_video_count = sum(1 for s in rc_scenes if s.get("type") == "video")
    actual_image_count = sum(1 for s in rc_scenes if s.get("type") != "video")

    video_info = ""
    if actual_video_count > 0:
        video_info = f"\n🎬 Video clips: {actual_video_count} animated, {actual_image_count} static images"
    elif actual_image_count > 0:
        video_info = f"\n🖼️ {actual_image_count} static images (no video clips)"

    sound_info = ""
    if sfx_count > 0:
        sound_info = f"\n🔊 Sound effects: {sfx_count}/{sfx_total} SFX files ready"
    elif sfx_total > 0:
        sound_info = f"\n⚠️ {sfx_total} SFX expected but 0 downloaded"
    else:
        sound_info = "\n🔇 No sound effects"

    music_info = ""
    if music_beds:
        music_info = f"\n🎵 Background music: {len(music_beds)} tracks"
    else:
        music_info = "\n🔇 No background music"

    pipeline.slack.notify(
        f"⬇️ *Assets ready:* _{pipeline.video_title}_\n"
        f"{scene_count} scenes, {audio_count} audio files verified."
        f"{video_info}{sound_info}{music_info}\n"
        f"Starting Remotion render now..."
    )

    # Run Remotion render
    render_result = await _run_remotion_render(pipeline, remotion_dir, public_dir, props_file, props)
    if render_result.get("error"):
        return render_result

    output_file = render_result["output_file"]
    file_size_mb = render_result["file_size_mb"]
    total_min = render_result["total_min"]
    folder_id = asset_folders[0][0] if asset_folders else None

    # Upload to Drive
    print("  ☁️ Uploading to Google Drive...")
    pipeline.slack.notify(
        f"✅ *Render complete:* _{pipeline.video_title}_ ({file_size_mb:.0f} MB, {total_min} min)\n"
        f"Uploading to Google Drive..."
    )

    safe_name = _sanitize(pipeline.video_title)
    with open(output_file, "rb") as f:
        video_content = f.read()

    drive_file = pipeline.google.upload_video(video_content, f"{safe_name}.mp4", folder_id)
    drive_url = f"https://drive.google.com/file/d/{drive_file['id']}/view"

    # Update Airtable
    pipeline.airtable.update_idea_fields(pipeline.current_idea_id, {
        IdeaFields.FINAL_VIDEO: drive_url,
        IdeaFields.FINAL_VIDEO_URL: drive_url,
    })
    pipeline._update_status(Statuses.RENDERED)

    del video_content
    _clean_render_assets(label="post-upload")

    print(f"  ✅ Status updated to: {Statuses.RENDERED}")
    print(f"  🔗 Video: {drive_url}")

    pipeline.slack.notify(
        f"✅ *Render complete:* _{pipeline.video_title}_\n"
        f"📺 *Drive link:* {drive_url}\n\n"
        f"Generating SEO metadata and uploading to YouTube next..."
    )

    return {
        "bot": "Render Bot",
        "video_title": pipeline.video_title,
        "new_status": Statuses.RENDERED,
        "video_url": drive_url,
    }


def _sanitize(title: str) -> str:
    """Sanitize a title for use as a filename."""
    clean = re.sub(r'[^\w\s-]', '', title)
    return re.sub(r'[-\s]+', '_', clean)[:50]


def _find_asset_folders(pipeline) -> list[tuple[str, str]]:
    """Find Drive folders containing scene assets."""
    asset_folders = []

    if pipeline.project_folder_id:
        files_in = pipeline.google.list_files_in_folder(pipeline.project_folder_id)
        scene_files = [f for f in files_in if f["name"].startswith("Scene")]
        if scene_files:
            asset_folders.append((pipeline.project_folder_id, f"saved ({len(scene_files)} scene files)"))

    if not asset_folders:
        if pipeline.project_folder_id:
            print(f"  ⚠️ Saved folder {pipeline.project_folder_id} has no Scene files, falling back to search")
        scored_folders = pipeline.google.find_folder_by_keywords(pipeline.video_title)
        for cand, score in scored_folders[:10]:
            files_in = pipeline.google.list_files_in_folder(cand["id"])
            scene_files = [f for f in files_in if f["name"].startswith("Scene")]
            if scene_files:
                asset_folders.append((cand["id"], f"{cand['name']} ({len(scene_files)} scene files, score:{score})"))
                break

    return asset_folders


async def _download_assets(pipeline, asset_folders, public_dir) -> dict:
    """Download scene assets from Drive folders."""
    SLACK_UPDATE_INTERVAL = 30

    download_queue: list[dict] = []
    seen_local: set[str] = set()

    for folder_id, folder_desc in asset_folders:
        drive_files = pipeline.google.list_files_in_folder(folder_id)
        for df in drive_files:
            fname = df["name"]
            fid = df["id"]

            is_audio = fname.startswith("Scene ") and fname.endswith(".mp3")
            is_image = fname.startswith("Scene_") and fname.endswith(".png")
            is_video = fname.endswith(".mp4")
            if not is_audio and not is_image and not is_video:
                continue

            local_fname = fname
            if is_video and not fname.startswith("Scene_"):
                nums = re.findall(r"(\d+)", fname)
                if len(nums) >= 2:
                    local_fname = f"Scene_{int(nums[0]):02d}_{int(nums[1]):02d}.mp4"
                else:
                    continue

            dest = public_dir / local_fname
            if dest.exists() or local_fname in seen_local:
                continue

            seen_local.add(local_fname)
            asset_type = "audio" if is_audio else ("video" if is_video else "image")
            download_queue.append({
                "fname": fname, "fid": fid,
                "dest": dest, "type": asset_type,
            })

    total_assets = len(download_queue)
    download_ok = 0
    download_fail = 0
    failed_assets = []
    audio_count = 0
    image_count = 0
    video_clip_count = 0

    last_slack_update = _time.time()

    pipeline.slack.notify(
        f"⬇️ *Downloading assets:* _{pipeline.video_title}_\n"
        f"`░░░░░░░░░░` *0%* — 0/{total_assets} files"
    )

    for item in download_queue:
        try:
            content = pipeline.google.download_file(item["fid"])
            if len(content) < 1000:
                raise ValueError(f"File too small ({len(content)} bytes)")
            item["dest"].write_bytes(content)
            print(f"    ✅ {item['fname']} ({len(content) // 1024} KB)")
            download_ok += 1
            if item["type"] == "audio":
                audio_count += 1
            elif item["type"] == "video":
                video_clip_count += 1
            else:
                image_count += 1
        except Exception as e:
            print(f"    ❌ {item['fname']} FAILED: {e}")
            failed_assets.append(item["fname"])
            download_fail += 1

        completed = download_ok + download_fail
        now = _time.time()
        if now - last_slack_update >= SLACK_UPDATE_INTERVAL and completed < total_assets:
            pct = (completed / total_assets * 100) if total_assets > 0 else 0
            bar = "█" * int(pct // 10) + "░" * (10 - int(pct // 10))
            pipeline.slack.notify(
                f"⬇️ *Downloading assets:* _{pipeline.video_title}_\n"
                f"`{bar}` *{pct:.1f}%* — {completed}/{total_assets} files "
                f"({audio_count} audio, {image_count} images, {video_clip_count} clips)"
            )
            last_slack_update = now

    return {
        "ok": download_ok, "fail": download_fail,
        "audio": audio_count, "images": image_count, "clips": video_clip_count,
        "failed_assets": failed_assets, "total": total_assets,
    }


def _patch_render_config_video_clips(props: dict, public_dir: Path):
    """Patch render_config entries for downloaded video clips."""
    if "renderConfig" not in props:
        return

    import glob as _glob_mod

    rc_data = props["renderConfig"]
    downloaded_mp4s = _glob_mod.glob(str(public_dir / "Scene_*.mp4"))
    mp4_lookup: dict[tuple[int, int], str] = {}
    for mp4_path in downloaded_mp4s:
        mp4_name = os.path.basename(mp4_path)
        match = re.match(r"Scene_(\d+)_(\d+)\.mp4", mp4_name)
        if match:
            mp4_lookup[(int(match.group(1)), int(match.group(2)))] = mp4_name

    patched = 0
    for rc_entry in rc_data.get("scenes", []):
        sn = rc_entry.get("scene_number", 0)
        ii = rc_entry.get("image_index", 0)
        mp4_name = mp4_lookup.get((sn, ii))
        if mp4_name:
            rc_entry["type"] = "video"
            rc_entry["video_clip_path"] = mp4_name
            patched += 1

    if patched:
        rc_path = public_dir / "render_config.json"
        with open(rc_path, "w") as f:
            json.dump(rc_data, f, indent=2)
        props["renderConfig"] = rc_data
        print(f"  🎬 Patched render_config: {patched} entries marked as video clips")


async def _download_sfx(pipeline, asset_folders, props: dict, public_dir: Path) -> tuple[int, int]:
    """Download per-image SFX files with 4-strategy fallback. Returns (downloaded, total)."""
    import httpx as _httpx

    # Build map of SFX files in Drive
    drive_sfx_map: dict[str, str] = {}
    for folder_id, _desc in asset_folders:
        drive_files = pipeline.google.list_files_in_folder(folder_id)
        for df in drive_files:
            if df["name"].startswith("sfx_") and df["name"].endswith(".mp3"):
                drive_sfx_map[df["name"]] = df["id"]

    sfx_dir = public_dir / "sfx"
    sfx_dir.mkdir(exist_ok=True)
    sfx_count = 0
    sfx_total = 0

    for scene in props.get("scenes", []):
        for image in scene.get("images", []):
            sfx_path = image.get("sfx")
            sfx_url = image.pop("sfxUrl", None)
            if not sfx_path or not sfx_url:
                continue
            sfx_total += 1
            filename = sfx_path.removeprefix("sfx/")
            dest = sfx_dir / filename
            if dest.exists() and dest.stat().st_size > 100:
                sfx_count += 1
                continue

            downloaded = False

            # Strategy 1: Drive file map
            if filename in drive_sfx_map:
                try:
                    content = pipeline.google.download_file(drive_sfx_map[filename])
                    dest.write_bytes(content)
                    print(f"    ✅ {filename} ({len(content) // 1024} KB) [Drive map]")
                    downloaded = True
                except Exception as e:
                    print(f"    ⚠️ Drive map download failed for {filename}: {e}")

            # Strategy 2: Search Drive by filename
            if not downloaded and pipeline.project_folder_id:
                try:
                    result = pipeline.google.search_file(filename, pipeline.project_folder_id)
                    if result:
                        content = pipeline.google.download_file(result["id"])
                        dest.write_bytes(content)
                        print(f"    ✅ {filename} ({len(content) // 1024} KB) [Drive search]")
                        downloaded = True
                except Exception as e:
                    print(f"    ⚠️ Drive search failed for {filename}: {e}")

            # Strategy 3: Extract Drive file ID from URL
            if not downloaded and sfx_url:
                drive_id = None
                if "/file/d/" in sfx_url:
                    try:
                        drive_id = sfx_url.split("/file/d/")[1].split("/")[0]
                    except (IndexError, AttributeError):
                        pass
                elif "id=" in sfx_url:
                    try:
                        drive_id = sfx_url.split("id=")[1].split("&")[0]
                    except (IndexError, AttributeError):
                        pass
                if drive_id:
                    try:
                        content = pipeline.google.download_file(drive_id)
                        dest.write_bytes(content)
                        print(f"    ✅ {filename} ({len(content) // 1024} KB) [Drive ID]")
                        downloaded = True
                    except Exception as e:
                        print(f"    ⚠️ Drive ID download failed for {filename}: {e}")

            # Strategy 4: Direct HTTP from CDN
            if not downloaded and sfx_url:
                try:
                    async with _httpx.AsyncClient() as http:
                        resp = await http.get(sfx_url, timeout=60.0, follow_redirects=True)
                        resp.raise_for_status()
                    dest.write_bytes(resp.content)
                    print(f"    ✅ {filename} ({len(resp.content) // 1024} KB) [CDN]")
                    downloaded = True
                except Exception as e:
                    print(f"    ⚠️ CDN download failed for {filename}: {e}")

            if downloaded:
                sfx_count += 1
            else:
                print(f"    ❌ {filename}: all download strategies failed")
                image.pop("sfx", None)
                image.pop("sfxVolume", None)

    print(f"  🔊 Sound effects: {sfx_count}/{sfx_total} SFX files downloaded")

    # Verify SFX on disk
    sfx_removed = 0
    for scene in props.get("scenes", []):
        for image in scene.get("images", []):
            sfx_path = image.get("sfx")
            if not sfx_path:
                continue
            full_path = public_dir / sfx_path
            if not full_path.exists() or full_path.stat().st_size < 100:
                print(f"    ⚠️ SFX missing/empty on disk, removing from props: {sfx_path}")
                image.pop("sfx", None)
                image.pop("sfxVolume", None)
                sfx_removed += 1
    if sfx_removed:
        print(f"  ⚠️ Removed {sfx_removed} SFX references (files not on disk)")

    return sfx_count, sfx_total


async def _verify_and_fetch_audio(pipeline, props: dict, public_dir: Path) -> list[str]:
    """Verify scene audio files exist, fetch from Airtable if missing. Returns list of still-missing."""
    import httpx as _httpx

    missing_audio = []
    for scene in props.get("scenes", []):
        scene_num = scene.get("sceneNumber", 0)
        audio_path = public_dir / f"Scene {scene_num}.mp3"
        if not audio_path.exists():
            missing_audio.append(f"Scene {scene_num}.mp3")

    if not missing_audio:
        return []

    # Fallback: fetch from Airtable Script table
    print(f"  ⚠️ {len(missing_audio)} audio files not found in Drive, trying Airtable fallback...")
    scripts = pipeline.airtable.get_scripts_by_title(pipeline.video_title)
    scripts_by_scene = {s.get("scene", 0): s for s in scripts}

    still_missing = []
    for fname in missing_audio:
        scene_num = int(fname.split("Scene ")[1].split(".mp3")[0])
        script = scripts_by_scene.get(scene_num)
        if not script:
            still_missing.append(fname)
            continue

        voice_over = script.get(ScriptFields.VOICE_OVER)
        voice_url = None
        if isinstance(voice_over, list) and voice_over:
            voice_url = voice_over[0].get("url")
        elif isinstance(voice_over, str):
            voice_url = voice_over

        if not voice_url:
            still_missing.append(fname)
            continue

        try:
            async with _httpx.AsyncClient() as http:
                resp = await http.get(voice_url, timeout=60.0, follow_redirects=True)
                resp.raise_for_status()
            dest = public_dir / fname
            dest.write_bytes(resp.content)
            print(f"    ✅ {fname} (from Airtable, {len(resp.content) // 1024} KB)")
        except Exception as e:
            print(f"    ❌ {fname} Airtable fallback failed: {e}")
            still_missing.append(fname)

    return still_missing


async def _run_remotion_render(pipeline, remotion_dir: Path, public_dir: Path,
                                props_file: Path, props: dict) -> dict:
    """Execute Remotion render and return result."""
    safe_name = _sanitize(pipeline.video_title)
    output_file = remotion_dir / "out" / f"{safe_name}.mp4"
    output_file.parent.mkdir(exist_ok=True)

    # Ensure node_modules
    if not (remotion_dir / "node_modules").exists():
        print(f"  📦 Installing Remotion dependencies...")
        install = subprocess.run(["npm", "install"], cwd=remotion_dir, capture_output=False)
        if install.returncode != 0:
            print(f"  ❌ npm install failed")
            pipeline.slack.notify(
                f"❌ *Render FAILED:* _{pipeline.video_title}_\n"
                f"`npm install` failed in remotion-video/. Check node/npm on VPS."
            )
            return {"error": "npm install failed", "bot": "Render Bot"}

    # Clear Remotion cache
    remotion_cache = remotion_dir / ".remotion"
    if remotion_cache.exists():
        shutil.rmtree(remotion_cache, ignore_errors=True)
        print(f"  🧹 Cleared Remotion bundle cache")

    # Render
    print(f"  🎥 Rendering video (concurrency=3, estimated 45-60 minutes)...")
    render_cmd = [
        "npx", "remotion", "render",
        "Main", str(output_file),
        "--props", str(props_file),
        "--concurrency=3",
        "--gl=swangle",
        "--timeout=180000",
        "--offthreadvideo-cache-size-in-bytes=1073741824",
    ]

    print(f"  🎯 Render cmd: {' '.join(str(c) for c in render_cmd)}")
    render_start = _time.time()
    last_update_frame = 0
    last_update_time = render_start
    FRAME_UPDATE_INTERVAL = 5000
    TIME_UPDATE_INTERVAL = 300
    last_error_line = ""

    process = subprocess.Popen(
        render_cmd, cwd=remotion_dir,
        stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
        text=True, bufsize=1,
    )

    for line in process.stdout:
        line = line.strip()
        if not line:
            continue
        print(f"    {line}")

        frame_match = re.search(r'Rendered\s+(\d+)/(\d+)', line)
        if frame_match:
            current_frame = int(frame_match.group(1))
            total_frames = int(frame_match.group(2))
            current_pct = (current_frame / total_frames * 100) if total_frames > 0 else 0
            now = _time.time()
            elapsed = now - render_start
            elapsed_min = int(elapsed / 60)
            frames_since_update = current_frame - last_update_frame
            time_since_update = now - last_update_time

            if frames_since_update >= FRAME_UPDATE_INTERVAL or time_since_update >= TIME_UPDATE_INTERVAL:
                if current_pct > 0:
                    total_est = elapsed / (current_pct / 100)
                    remaining_min = int((total_est - elapsed) / 60)
                    eta_str = f"~{remaining_min} min remaining"
                else:
                    eta_str = "estimating..."

                progress_bar = "█" * int(current_pct // 10) + "░" * (10 - int(current_pct // 10))
                pipeline.slack.notify(
                    f"🎬 *Render progress:* _{pipeline.video_title}_\n"
                    f"`{progress_bar}` *{current_pct:.1f}%* — frame {current_frame}/{total_frames} — {elapsed_min} min elapsed, {eta_str}"
                )
                last_update_frame = current_frame
                last_update_time = now

        if "error" in line.lower() or "Error" in line:
            last_error_line = line

    returncode = process.wait()
    total_min = int((_time.time() - render_start) / 60)

    if returncode != 0:
        print(f"  ❌ Render failed")
        error_detail = f"\n`{last_error_line}`" if last_error_line else ""
        pipeline.slack.notify(
            f"❌ *Render FAILED:* _{pipeline.video_title}_\n"
            f"Remotion exited with code {returncode} after {total_min} min.{error_detail}"
        )
        return {"error": "Render failed", "bot": "Render Bot"}

    if not output_file.exists():
        print(f"  ❌ Output not found")
        pipeline.slack.notify(
            f"❌ *Render FAILED:* _{pipeline.video_title}_\n"
            f"Remotion finished but output file not found at {output_file}"
        )
        return {"error": "Output file missing", "bot": "Render Bot"}

    file_size_mb = output_file.stat().st_size / (1024 * 1024)
    print(f"  ✅ Rendered: {output_file} ({file_size_mb:.0f} MB)")

    return {
        "output_file": output_file,
        "file_size_mb": file_size_mb,
        "total_min": total_min,
    }


async def _select_and_download_music(pipeline, props: dict, public_dir: Path) -> list[dict]:
    """Select per-act background music based on mood classification.

    Uses Claude Haiku to classify each act's mood (tension/strategic/revelation)
    and selects a random track from the music library matching that mood.

    Returns list of music_bed dicts with: act, file, mood, volume
    """
    from bots.music_selector import select_music_for_script, MUSIC_FOLDER_ID

    # Get render_config to extract act boundaries
    rc_data = props.get("renderConfig", {})
    rc_scenes = rc_data.get("scenes", [])
    if not rc_scenes:
        print("  ⚠️ No scenes in renderConfig, skipping music selection")
        return []

    # Build scene-to-act mapping
    scene_to_act: dict[int, int] = {}
    for scene in rc_scenes:
        scene_num = scene.get("scene_number", 0)
        act_num = scene.get("act", 0)
        if scene_num and act_num:
            scene_to_act[scene_num] = act_num

    if not scene_to_act:
        print("  ⚠️ No act data in renderConfig, estimating from scene numbers")
        for i in range(1, 21):
            scene_to_act[i] = min(6, (i - 1) // 3 + 1)

    # Get script text from Airtable
    scripts = pipeline.airtable.get_scripts_by_title(pipeline.video_title)
    if not scripts:
        print("  ⚠️ No scripts found, skipping music selection")
        return []

    # Group script text by act
    acts: dict[int, str] = {}
    for script in sorted(scripts, key=lambda s: s.get("scene", 0)):
        scene_text = script.get(ScriptFields.SCENE_TEXT, "")
        scene_num = script.get("scene", 0)
        act_num = scene_to_act.get(scene_num, 1)

        if act_num not in acts:
            acts[act_num] = ""
        acts[act_num] += f"\n{scene_text}"

    if not acts:
        print("  ⚠️ Could not group scripts by act, skipping music")
        return []

    print(f"  🎵 Selecting background music for {len(acts)} acts...")

    # Create Anthropic client and select music
    from clients.anthropic_client import AnthropicClient
    anthropic = AnthropicClient()
    music_beds = await select_music_for_script(anthropic, acts)

    if not music_beds:
        print("  ⚠️ No music tracks selected")
        return []

    # Download music files to public/music/
    music_dir = public_dir / "music"
    music_dir.mkdir(exist_ok=True)

    # Get list of files in the music library folder
    try:
        music_files = pipeline.google.list_files_in_folder(MUSIC_FOLDER_ID)
        music_map = {f["name"]: f["id"] for f in music_files}
    except Exception as e:
        print(f"  ⚠️ Could not list music folder: {e}")
        return []

    downloaded = []
    for bed in music_beds:
        if not bed.get("file"):
            continue

        filename = bed["file"].removeprefix("music/")
        dest = music_dir / filename

        if dest.exists() and dest.stat().st_size > 1000:
            print(f"    ✅ {filename} (cached)")
            downloaded.append(bed)
            continue

        file_id = bed.get("file_id") or music_map.get(filename)
        if not file_id:
            print(f"    ❌ {filename}: not found in music library")
            continue

        try:
            content = pipeline.google.download_file(file_id)
            dest.write_bytes(content)
            print(f"    ✅ {filename} ({len(content) // 1024} KB)")
            downloaded.append(bed)
        except Exception as e:
            print(f"    ❌ {filename}: download failed: {e}")

    # Notify Slack
    if downloaded:
        mood_emoji = {"tension": "😰", "strategic": "♟️", "revelation": "💡"}
        lines = ["🎵 *Background Music Selected:*"]
        for bed in sorted(downloaded, key=lambda b: b.get("act", 0)):
            act = bed.get("act", "?")
            mood = bed.get("mood", "unknown")
            track = bed.get("file", "").split("/")[-1]
            emoji = mood_emoji.get(mood, "🎵")
            lines.append(f"  Act {act}: {emoji} {mood} → `{track}`")
        pipeline.slack.notify("\n".join(lines))

    # Return music_beds with file paths (no file_id needed in render_config)
    return [
        {
            "act": b["act"],
            "file": b["file"],
            "mood": b["mood"],
            "volume": b["volume"],
        }
        for b in downloaded
    ]
