import type {SceneControlSnapshot} from "./scene-control-types";

const hash = (character: string): string => character.repeat(64);

const artifactSet = (shot: number) => [
  {
    id: `storyboard-${shot}`,
    label: "Storyboard",
    kind: "storyboard" as const,
    status: "approved" as const,
    deterministic: true,
    detail: "Local synthetic board",
  },
  {
    id: `image-${shot}`,
    label: "Final image",
    kind: "image" as const,
    status: "ready_for_review" as const,
    deterministic: false,
    detail: "Synthetic stand-in; no provider media",
  },
  {
    id: `animation-${shot}`,
    label: "Motion",
    kind: "animation" as const,
    status: "missing" as const,
    deterministic: false,
  },
];

export const SCENE_CONTROL_SYNTHETIC_FIXTURE: SceneControlSnapshot = {
  film_id: "synthetic-film-scene-control",
  title: "Relay Room Signal — synthetic control proof",
  film_revision_hash: hash("a"),
  film_locks_approved: true,
  film_locks: [
    {
      id: "story",
      label: "Story throughline",
      summary: "Mara and Elias contain an internal relay threat and recover the trace that drives Scene 2.",
      status: "locked",
      revision_hash: hash("1"),
      reviewable: true,
    },
    {
      id: "dialogue",
      label: "Dialogue ownership",
      summary: "Mara and Elias own four exact lines; Shots 1, 3, and 5 are intentional silent action.",
      status: "locked",
      revision_hash: hash("5"),
      reviewable: true,
    },
    {
      id: "style",
      label: "Visual grammar",
      summary: "Grounded nocturnal sci-fi, restrained camera, turquoise-to-red practical relay light.",
      status: "locked",
      revision_hash: hash("2"),
      reviewable: true,
    },
    {
      id: "cast",
      label: "Recurring cast",
      summary: "Mara and Elias retain fixed silhouettes, wardrobe, and screen position.",
      status: "locked",
      revision_hash: hash("3"),
      reviewable: true,
    },
    {
      id: "environments",
      label: "Recurring environment",
      summary: "Relay console, breaker wall, and character geography remain immutable.",
      status: "locked",
      revision_hash: hash("4"),
      reviewable: true,
    },
    {
      id: "techniques",
      label: "Technique boundaries",
      summary: "Dialogue exchanges and silent cinematic action may vary without changing film identity.",
      status: "locked",
      revision_hash: hash("6"),
      reviewable: true,
    },
  ],
  current_scene_id: "scene-control-scene-1",
  scenes: [
    {
      id: "scene-control-scene-1",
      number: 1,
      title: "The internal signal",
      purpose: "Contain the relay threat and recover the evidence that opens the next scene.",
      target_duration_seconds: 18,
      story_time: "Night 1 · relay breach",
      state: "plan_approved",
      rail_status: "current",
      revision_hash: hash("b"),
      transition_evidence_hashes: {
        storyboard_approved: hash("e"),
        imagery_approved: hash("f"),
        animation_approved: hash("7"),
        audio_approved: hash("8"),
        assembled: hash("9"),
        accepted: hash("0"),
      },
      environment_label: "Relay room",
      character_labels: ["Mara", "Elias"],
      shots: [
        {
          id: "scene-control-shot-1",
          shot_key: "establish_relay_room",
          order: 1,
          title: "Establish the relay room",
          duration_seconds: 3,
          narrative_function: "Establish both characters, relay-room geography, and the amber key.",
          advancement: "Mara seats the key that starts the conflict while Elias holds the breaker wall.",
          opening_state: "Mara stands left of the relay console; Elias watches from the breaker wall.",
          closing_state: "Mara reaches the console and inserts the amber key while Elias holds position.",
          character_action: "Mara crosses to the console and inserts the key; Elias holds.",
          camera_action: "Geographic establishing move from console to breaker wall.",
          transition: "Opening",
          continuity_inputs: ["Mara left of relay console", "Elias at breaker wall"],
          continuity_outputs: ["Amber key seated", "Character geography locked"],
          performance_mode: "silent_action",
          dialogue: [],
          artifacts: artifactSet(1),
        },
        {
          id: "scene-control-shot-2",
          shot_key: "signal_exchange",
          order: 2,
          title: "Identify the internal signal",
          duration_seconds: 4,
          narrative_function: "Turn the unexplained signal into an immediate shared threat.",
          advancement: "Mara identifies the signal as internal; Elias realizes it can detect them.",
          opening_state: "The amber key is seated and the relay line glows turquoise between Mara and Elias.",
          closing_state: "Mara identifies the signal as internal; Elias realizes the intruder can detect them.",
          character_action: "Mara reads the console; Elias tracks the live line.",
          camera_action: "Alternating eyelines across the glowing relay line.",
          transition: "Continuous",
          continuity_inputs: ["Amber key seated", "Turquoise relay line active"],
          continuity_outputs: ["Internal signal identified", "Detection risk shared"],
          performance_mode: "dialogue",
          dialogue: [
            {
              id: "scene-control-shot-2-line-1",
              speaker_id: "scene_control_character_mara",
              speaker_label: "Mara",
              text: "The signal is inside.",
              performance_intent: "Controlled realization",
              start_seconds: 3.25,
              end_seconds: 4.92,
            },
            {
              id: "scene-control-shot-2-line-2",
              speaker_id: "scene_control_character_elias",
              speaker_label: "Elias",
              text: "Then it knows we're here.",
              performance_intent: "Immediate tactical alarm",
              start_seconds: 5,
              end_seconds: 6.83,
            },
          ],
          artifacts: artifactSet(2),
        },
        {
          id: "scene-control-shot-3",
          shot_key: "silent_alarm_beat",
          order: 3,
          title: "Let the alarm become visible",
          duration_seconds: 3,
          narrative_function: "Make the threat visible before the characters decide.",
          advancement: "The turquoise line expands red and drives both characters toward the center.",
          opening_state: "Mara and Elias face the live turquoise relay line.",
          closing_state: "The line expands red across the console and both characters recoil toward the center.",
          character_action: "Both recoil as the relay line changes state.",
          camera_action: "Continuous reaction beat holding the established geography.",
          transition: "Continuous",
          continuity_inputs: ["Internal signal identified", "Turquoise line active"],
          continuity_outputs: ["Relay line red", "Both characters centered"],
          performance_mode: "silent_action",
          dialogue: [],
          artifacts: artifactSet(3),
        },
        {
          id: "scene-control-shot-4",
          shot_key: "breaker_exchange",
          order: 4,
          title: "Coordinate the breaker action",
          duration_seconds: 4,
          narrative_function: "Convert discovery into a decisive coordinated response.",
          advancement: "Mara orders the shutdown as Elias reveals he already anticipated it.",
          opening_state: "The red relay line is active; Elias is nearest the breaker wall.",
          closing_state: "Mara orders the transmitter killed as Elias reaches the breaker and reveals he anticipated her.",
          character_action: "Mara commands from the console; Elias reaches the breaker.",
          camera_action: "Continuous cross-room dialogue preserving screen direction.",
          transition: "Continuous",
          continuity_inputs: ["Red relay line active", "Elias nearest breaker"],
          continuity_outputs: ["Shutdown command given", "Elias at breaker"],
          performance_mode: "dialogue",
          dialogue: [
            {
              id: "scene-control-shot-4-line-1",
              speaker_id: "scene_control_character_mara",
              speaker_label: "Mara",
              text: "Kill the transmitter.",
              performance_intent: "Immediate command",
              start_seconds: 10.25,
              end_seconds: 11.92,
            },
            {
              id: "scene-control-shot-4-line-2",
              speaker_id: "scene_control_character_elias",
              speaker_label: "Elias",
              text: "Already did.",
              performance_intent: "Calm confirmation",
              start_seconds: 12,
              end_seconds: 13.83,
            },
          ],
          artifacts: artifactSet(4),
        },
        {
          id: "scene-control-shot-5",
          shot_key: "breaker_payoff",
          order: 5,
          title: "Pay off the breaker and key",
          duration_seconds: 4,
          narrative_function: "Resolve the immediate threat and create the evidence for Scene 2.",
          advancement: "Elias collapses the relay and the console releases a paper trace to Mara.",
          opening_state: "Elias has reached the breaker; Mara remains beside the overloaded console.",
          closing_state: "Elias throws the breaker, the relay collapses, and the console releases a paper trace to Mara.",
          character_action: "Elias throws the breaker; Mara catches the released trace.",
          camera_action: "Time cut to breaker payoff, then return to Mara and the trace.",
          transition: "Time cut",
          continuity_inputs: ["Elias at breaker", "Mara beside overloaded console"],
          continuity_outputs: ["Relay collapsed", "Paper trace recovered"],
          performance_mode: "silent_action",
          dialogue: [],
          artifacts: artifactSet(5),
        },
      ],
    },
    {
      id: "scene-control-scene-2",
      number: 2,
      title: "Read the trace",
      purpose: "Follow the evidence recovered from the relay.",
      target_duration_seconds: 24,
      story_time: "Immediately after the relay breach",
      state: "draft",
      rail_status: "locked",
      revision_hash: hash("c"),
      transition_evidence_hashes: {},
      environment_label: "Relay room",
      character_labels: ["Mara", "Elias"],
      shots: [
        {
          id: "scene-control-scene-2-placeholder",
          shot_key: "locked_placeholder",
          order: 1,
          title: "Locked until Scene 1 is accepted",
          duration_seconds: 24,
          narrative_function: "Await accepted continuity.",
          advancement: "Unavailable while the prior scene remains open.",
          opening_state: "Inherited only after Scene 1 acceptance.",
          closing_state: "Not yet planned.",
          character_action: "Locked",
          camera_action: "Locked",
          transition: "Locked",
          continuity_inputs: [],
          continuity_outputs: [],
          performance_mode: "silent_action",
          dialogue: [],
          artifacts: [],
        },
      ],
    },
  ],
  next_operation: {
    quote_version: 1,
    video_id: "synthetic-film-scene-control",
    scene_id: "scene-control-scene-1",
    scene_number: 1,
    shot_ids: [
      "scene-control-shot-1",
      "scene-control-shot-2",
      "scene-control-shot-3",
      "scene-control-shot-4",
      "scene-control-shot-5",
    ],
    operation_type: "storyboard_images",
    provider_operation: "storyboard_image",
    deterministic: false,
    initial_calls: 5,
    max_repair_calls: 0,
    unit_max_cents: 5,
    exact_incremental_max_cents: 25,
    prior_completed_cumulative_spend_cents: 0,
    new_exact_cumulative_ceiling_cents: 25,
    included_media: ["Five storyboard images for Scene 1"],
    explicitly_unapproved: [
      "Final pictures",
      "Animation",
      "Voices",
      "Helper imagery",
      "Provider fallback",
    ],
    approval_status: "not_approved",
    approval_card_hash: hash("d"),
    scene_revision_hash: hash("b"),
  },
};
