import type {
  KalshiMarket,
  KalshiEvent,
  KalshiOrderbook,
  KalshiPosition,
  KalshiBalance,
  KalshiFill,
} from "./kalshi-types";

// Realistic geopolitics prediction markets for demo/development mode
export const mockMarkets: KalshiMarket[] = [
  {
    ticker: "CHINA-TAIWAN-2026",
    event_ticker: "CHINA-TAIWAN",
    title: "Will China impose a naval blockade on Taiwan before 2027?",
    status: "open",
    yes_bid: 8,
    yes_ask: 11,
    no_bid: 89,
    no_ask: 92,
    last_price: 9,
    volume: 284310,
    volume_24h: 12450,
    open_interest: 89200,
    close_time: "2026-12-31T23:59:59Z",
    category: "Geopolitics",
  },
  {
    ticker: "NATO-MEMBER-2026",
    event_ticker: "NATO-EXPANSION",
    title: "Will a new country begin NATO accession process in 2026?",
    status: "open",
    yes_bid: 22,
    yes_ask: 26,
    no_bid: 74,
    no_ask: 78,
    last_price: 24,
    volume: 156780,
    volume_24h: 8920,
    open_interest: 45600,
    close_time: "2026-12-31T23:59:59Z",
    category: "Geopolitics",
  },
  {
    ticker: "RUSSIA-UKRAINE-CEASE",
    event_ticker: "RUSSIA-UKRAINE",
    title: "Will Russia and Ukraine agree to a ceasefire by July 2026?",
    status: "open",
    yes_bid: 14,
    yes_ask: 18,
    no_bid: 82,
    no_ask: 86,
    last_price: 16,
    volume: 523400,
    volume_24h: 31200,
    open_interest: 167800,
    close_time: "2026-07-01T23:59:59Z",
    category: "Geopolitics",
  },
  {
    ticker: "IRAN-NUCLEAR-DEAL",
    event_ticker: "IRAN-NUCLEAR",
    title: "Will the US and Iran reach a new nuclear agreement in 2026?",
    status: "open",
    yes_bid: 6,
    yes_ask: 10,
    no_bid: 90,
    no_ask: 94,
    last_price: 8,
    volume: 98450,
    volume_24h: 4560,
    open_interest: 32100,
    close_time: "2026-12-31T23:59:59Z",
    category: "Geopolitics",
  },
  {
    ticker: "OIL-ABOVE-100",
    event_ticker: "OIL-PRICE",
    title: "Will Brent crude oil exceed $100/barrel before July 2026?",
    status: "open",
    yes_bid: 31,
    yes_ask: 35,
    no_bid: 65,
    no_ask: 69,
    last_price: 33,
    volume: 412300,
    volume_24h: 23100,
    open_interest: 134500,
    close_time: "2026-07-01T23:59:59Z",
    category: "Economy",
  },
  {
    ticker: "CHINA-SANCTIONS-2026",
    event_ticker: "CHINA-SANCTIONS",
    title: "Will the US impose new semiconductor sanctions on China in Q2 2026?",
    status: "open",
    yes_bid: 62,
    yes_ask: 66,
    no_bid: 34,
    no_ask: 38,
    last_price: 64,
    volume: 287600,
    volume_24h: 15800,
    open_interest: 89400,
    close_time: "2026-06-30T23:59:59Z",
    category: "Geopolitics",
  },
  {
    ticker: "BRICS-CURRENCY-2026",
    event_ticker: "BRICS-CURRENCY",
    title: "Will BRICS announce a common trade currency in 2026?",
    status: "open",
    yes_bid: 4,
    yes_ask: 7,
    no_bid: 93,
    no_ask: 96,
    last_price: 5,
    volume: 145200,
    volume_24h: 6780,
    open_interest: 41200,
    close_time: "2026-12-31T23:59:59Z",
    category: "Economy",
  },
  {
    ticker: "EU-TARIFF-CHINA",
    event_ticker: "EU-TRADE",
    title: "Will the EU impose new tariffs on Chinese EVs before September 2026?",
    status: "open",
    yes_bid: 71,
    yes_ask: 75,
    no_bid: 25,
    no_ask: 29,
    last_price: 73,
    volume: 198700,
    volume_24h: 11200,
    open_interest: 67800,
    close_time: "2026-09-01T23:59:59Z",
    category: "Geopolitics",
  },
  {
    ticker: "KOREA-SUMMIT-2026",
    event_ticker: "KOREA-RELATIONS",
    title: "Will North and South Korea hold a formal summit in 2026?",
    status: "open",
    yes_bid: 3,
    yes_ask: 6,
    no_bid: 94,
    no_ask: 97,
    last_price: 4,
    volume: 67800,
    volume_24h: 2340,
    open_interest: 18900,
    close_time: "2026-12-31T23:59:59Z",
    category: "Geopolitics",
  },
  {
    ticker: "FED-RATE-CUT-JUN",
    event_ticker: "FED-RATES",
    title: "Will the Fed cut rates at the June 2026 FOMC meeting?",
    status: "open",
    yes_bid: 45,
    yes_ask: 49,
    no_bid: 51,
    no_ask: 55,
    last_price: 47,
    volume: 892300,
    volume_24h: 67800,
    open_interest: 312400,
    close_time: "2026-06-18T23:59:59Z",
    category: "Economy",
  },
  {
    ticker: "MIDEAST-PEACE-2026",
    event_ticker: "MIDEAST-PEACE",
    title: "Will Israel and Hamas reach a permanent ceasefire agreement in 2026?",
    status: "open",
    yes_bid: 18,
    yes_ask: 22,
    no_bid: 78,
    no_ask: 82,
    last_price: 20,
    volume: 678900,
    volume_24h: 45600,
    open_interest: 234500,
    close_time: "2026-12-31T23:59:59Z",
    category: "Geopolitics",
  },
  {
    ticker: "INDIA-GDP-GROWTH",
    event_ticker: "INDIA-ECONOMY",
    title: "Will India's GDP growth exceed 7% in Q2 2026?",
    status: "open",
    yes_bid: 38,
    yes_ask: 42,
    no_bid: 58,
    no_ask: 62,
    last_price: 40,
    volume: 123400,
    volume_24h: 7890,
    open_interest: 45600,
    close_time: "2026-07-31T23:59:59Z",
    category: "Economy",
  },
  {
    ticker: "VENEZUELA-ELECTION",
    event_ticker: "LATAM-POLITICS",
    title: "Will Venezuela hold internationally recognized elections in 2026?",
    status: "open",
    yes_bid: 7,
    yes_ask: 11,
    no_bid: 89,
    no_ask: 93,
    last_price: 9,
    volume: 56700,
    volume_24h: 2340,
    open_interest: 14500,
    close_time: "2026-12-31T23:59:59Z",
    category: "Geopolitics",
  },
  {
    ticker: "USD-RESERVE-STATUS",
    event_ticker: "USD-DOMINANCE",
    title: "Will the US dollar's share of global reserves drop below 55% in 2026?",
    status: "open",
    yes_bid: 11,
    yes_ask: 15,
    no_bid: 85,
    no_ask: 89,
    last_price: 13,
    volume: 234500,
    volume_24h: 12300,
    open_interest: 78900,
    close_time: "2026-12-31T23:59:59Z",
    category: "Economy",
  },
  {
    ticker: "SOUTH-CHINA-SEA",
    event_ticker: "SOUTH-CHINA-SEA",
    title: "Will there be a military confrontation in the South China Sea in 2026?",
    status: "open",
    yes_bid: 16,
    yes_ask: 20,
    no_bid: 80,
    no_ask: 84,
    last_price: 18,
    volume: 345600,
    volume_24h: 19800,
    open_interest: 112300,
    close_time: "2026-12-31T23:59:59Z",
    category: "Geopolitics",
  },
];

export const mockEvents: KalshiEvent[] = [
  {
    event_ticker: "CHINA-TAIWAN",
    title: "China-Taiwan Relations",
    category: "Geopolitics",
    mutually_exclusive: false,
    markets: mockMarkets.filter((m) => m.event_ticker === "CHINA-TAIWAN"),
  },
  {
    event_ticker: "RUSSIA-UKRAINE",
    title: "Russia-Ukraine Conflict",
    category: "Geopolitics",
    mutually_exclusive: false,
    markets: mockMarkets.filter((m) => m.event_ticker === "RUSSIA-UKRAINE"),
  },
  {
    event_ticker: "FED-RATES",
    title: "Federal Reserve Rate Decisions",
    category: "Economy",
    mutually_exclusive: false,
    markets: mockMarkets.filter((m) => m.event_ticker === "FED-RATES"),
  },
];

export function getMockOrderbook(ticker: string): KalshiOrderbook {
  const market = mockMarkets.find((m) => m.ticker === ticker);
  const baseYes = market?.yes_bid ?? 50;

  return {
    yes: [
      { price: baseYes, quantity: 450 },
      { price: baseYes - 1, quantity: 320 },
      { price: baseYes - 2, quantity: 680 },
      { price: baseYes - 3, quantity: 210 },
      { price: baseYes - 5, quantity: 890 },
    ],
    no: [
      { price: 100 - baseYes, quantity: 380 },
      { price: 100 - baseYes - 1, quantity: 520 },
      { price: 100 - baseYes - 2, quantity: 290 },
      { price: 100 - baseYes - 3, quantity: 710 },
      { price: 100 - baseYes - 5, quantity: 440 },
    ],
  };
}

export const mockBalance: KalshiBalance = {
  balance: 5000, // $50.00 in cents
  portfolio_value: 5340, // $53.40
};

export const mockPositions: KalshiPosition[] = [
  {
    ticker: "CHINA-SANCTIONS-2026",
    event_ticker: "CHINA-SANCTIONS",
    market_exposure: 640,
    realized_pnl: 0,
    resting_orders_count: 0,
    total_traded: 10,
    position: 10, // 10 Yes contracts
  },
  {
    ticker: "FED-RATE-CUT-JUN",
    event_ticker: "FED-RATES",
    market_exposure: 470,
    realized_pnl: 120,
    resting_orders_count: 1,
    total_traded: 15,
    position: -5, // 5 No contracts
  },
];

export const mockFills: KalshiFill[] = [
  {
    trade_id: "fill-001",
    ticker: "CHINA-SANCTIONS-2026",
    side: "yes",
    action: "buy",
    count: 10,
    yes_price: 62,
    no_price: 38,
    created_time: "2026-03-20T14:30:00Z",
  },
  {
    trade_id: "fill-002",
    ticker: "FED-RATE-CUT-JUN",
    side: "no",
    action: "buy",
    count: 5,
    yes_price: 48,
    no_price: 52,
    created_time: "2026-03-21T09:15:00Z",
  },
];
