// Load per-video render configuration from render_config.json
// Generated by the audio_sync pipeline (replaces old segmentData.ts approach)

import { staticFile } from "remotion";

export interface RenderScene {
    scene_number: number;
    image_path: string;
    display_start: number;
    display_end: number;
    display_duration: number;
    narration_start: number;
    narration_end: number;
    style: string;
    composition: string;
    act: number;
    ken_burns: Record<string, unknown>;
    transition_in: Record<string, unknown>;
    transition_out: Record<string, unknown>;
}

export interface RenderConfig {
    video_id: string;
    audio_path: string;
    total_duration_seconds: number;
    fps: number;
    resolution: {
        width: number;
        height: number;
    };
    scenes: RenderScene[];
}

/**
 * Segment text data derived from render_config scenes.
 * Replaces the old SegmentText interface from segmentData.ts.
 */
export interface SegmentText {
    text: string;
    duration: number;
}

// Module-level cache for loaded render config
let _cachedConfig: RenderConfig | null = null;

/**
 * Load render_config.json from the public/ directory.
 * Returns null if the file doesn't exist (fallback to even distribution).
 */
export function loadRenderConfig(): RenderConfig | null {
    if (_cachedConfig) return _cachedConfig;

    try {
        // In Remotion, public/ files are accessed via staticFile()
        // For build-time loading, we try require() first
        // eslint-disable-next-line @typescript-eslint/no-var-requires
        const config = require("../../public/render_config.json") as RenderConfig;
        _cachedConfig = config;
        return config;
    } catch {
        // render_config.json not present — pipeline hasn't generated it yet
        return null;
    }
}

/**
 * Get the number of scenes from render config.
 * Groups render_config scenes by scene_number (multiple images may share a scene).
 */
export function getSceneCount(): number {
    const config = loadRenderConfig();
    if (!config || config.scenes.length === 0) return 0;

    const sceneNumbers = new Set(config.scenes.map((s) => s.scene_number));
    return sceneNumbers.size;
}

/**
 * Get render_config scenes for a specific scene number.
 * Each returned entry represents one image with its display timing.
 */
export function getRenderScenesForScene(sceneNumber: number): RenderScene[] {
    const config = loadRenderConfig();
    if (!config) return [];

    return config.scenes.filter((s) => s.scene_number === sceneNumber);
}

/**
 * Get image count for a scene from render config.
 */
export function getImageCountForScene(sceneNumber: number): number {
    return getRenderScenesForScene(sceneNumber).length;
}
