// Auto-generated segment data from Airtable
// Video: Citizenship Arbitrage 2030: The $500K Passport Portfolio That Replaces Nationality
// Generated for word-to-image alignment in Remotion

export interface SegmentText {
    text: string;
    duration: number;
}

export const sceneSegmentData: Record<number, SegmentText[]> = {
    1: [
        { text: "Forget choosing one safe haven. By 2030, the new wealthy elite won't have a home country,", duration: 10.0 },
        { text: "they'll have a portfolio of citizenships, each optimised for a different economic function.", duration: 10.0 },
        { text: "Here's the arbitrage strategy that makes migration obsolete. Right now, while you're watching", duration: 10.0 },
        { text: "this, over 40,000 individuals are assembling what wealth advisers quietly call Passport Portfolios,", duration: 10.0 },
        { text: "strategic combinations of citizenships that function like diversified investments,", duration: 10.0 },
        { text: "a fourth as pure insurance against political collapse. This isn't about fleeing your country,", duration: 10.0 },
        { text: "it's about treating nationality itself as an asset class, one you can stack, hedge,", duration: 6.0 },
        { text: "The ultra wealthy discovered something the rest of us were never taught. Citizenship is a product,", duration: 6.0 },
        { text: "The difference between the right combination and the wrong one, potentially millions in lifetime tax savings,", duration: 6.0 },
        { text: "The $500,000 question isn't whether this strategy works, it's whether you can still afford to execute it", duration: 10.0 },
    ],
    2: [
        { text: "Every single month, money vanishes from your account. You never approved it. You barely notice it. But the banks? They're counting on exactly that.", duration: 8.6 },
        { text: "Let's break down what you're actually paying. That wire transfer? Thirty dollars. The account they call free? It's costing you twelve dollars monthly in hidden minimums.", duration: 9.3 },
        { text: "And your savings account—sitting there earning half a percent while inflation burns through your purchasing power at three, four, sometimes five percent annually. You're losing money just by holding it.", duration: 10.0 },
        { text: "Now multiply this across every Canadian household. The average family hands over twenty-four hundred dollars every single year to the Big Five. Not for better service. Not for innovation.", duration: 10.0 },
        { text: "For the privilege of accessing their own money. That's two hundred dollars a month. Enough for groceries. Enough for a car payment. Gone.", duration: 8.2 },
        { text: "And here's what makes this predatory: these fees aren't competitive. They're coordinated. When TD raises their wire transfer cost, Royal Bank follows within weeks. When Scotiabank adjusts overdraft penalties, the others match.", duration: 10.0 },
        { text: "This isn't a market. This is a cartel operating in plain sight. And in twenty twenty-six, the entire structure faces something it never anticipated.", duration: 8.6 },
        { text: "Return JSON with segments array. Each segment has text and image_prompt.", duration: 6.0 },
    ],
    3: [
        { text: "The question isn't whether this technology works. It's already working.", duration: 6.0 },
        { text: "Right now, in seventeen countries, people are transferring money across borders in seconds—not days.", duration: 6.0 },
        { text: "They're paying fractions of a penny—not thirty dollars. They're watching their transactions settle in real time on a transparent ledger.", duration: 7.8 },
        { text: "So the real question becomes something far more dangerous. What happens when two million Canadians discover they've been paying a monopoly tax?", duration: 8.5 },
        { text: "What happens when they realize every wire transfer, every currency exchange, every international payment has been skimming profit into a system designed before the internet?", duration: 9.7 },
        { text: "And what happens when they find the exit door? Because that door is opening.", duration: 6.0 },
        { text: "The leaked documents we've obtained point to a specific timeline. A convergence of regulatory deadlines, technological adoption curves, and institutional vulnerabilities—all intersecting in 2026.", duration: 9.3 },
        { text: "The banks see it coming. The internal memos prove it. They're not preparing to compete. They're preparing to survive. And the clock is already ticking.", duration: 9.7 },
    ],
    4: [
        { text: "I know exactly what you're thinking right now. This sounds like crypto bro nonsense. Another breathless prediction from someone who bought Bitcoin at the top and needs you to validate their bags.", duration: 10.0 },
        { text: "But stop. That's not what this is. I'm not talking about speculative tokens. I'm not talking about dog coins or celebrity pump-and-dumps or whatever Ponzi scheme collapsed last week.", duration: 10.0 },
        { text: "I'm talking about regulated digital currency. Stablecoins pegged one-to-one with Canadian dollars, backed by actual reserves, audited quarterly. These instruments aren't theoretical—they're already being tested inside credit union networks.", duration: 10.0 },
        { text: "Operating within existing financial law. Supervised by provincial regulators who've spent decades protecting depositors. The documents I've obtained don't come from Reddit threads or anonymous Telegram groups.", duration: 9.8 },
        { text: "They come from internal bank communications, regulatory filings, and investment committee minutes that were never meant to reach the public.", duration: 7.3 },
        { text: "This is economics. This is infrastructure. This is the plumbing underneath the financial system that most people never think about until it stops working.", duration: 8.7 },
        { text: "And the people who understand this plumbing? They're positioning themselves right now. The question is whether you'll understand it in time.", duration: 7.6 },
        { text: "The question is whether you'll understand it in time.", duration: 6.0 },
    ],
    5: [
        { text: "In 2010, Blockbuster had ten thousand stores, billions in revenue, and absolute market dominance. Five years later, they were gone.", duration: 8.4 },
        { text: "And here's what everyone gets wrong about that collapse. Netflix didn't kill Blockbuster by being a slightly better video store.", duration: 8.4 },
        { text: "Netflix killed Blockbuster by eliminating the need for video stores entirely. Streaming didn't compete with the distribution layer. It erased it.", duration: 8.8 },
        { text: "This is the pattern that precedes every industry extinction event. The telegraph didn't lose to a faster telegraph.", duration: 7.5 },
        { text: "Kodak didn't fall to better film. Horse breeders didn't get outcompeted by superior horses. The entire category became obsolete.", duration: 8.0 },
        { text: "Now apply this framework to banking. The threat facing Canadian financial institutions isn't a fintech startup offering lower fees or better apps.", duration: 9.2 },
        { text: "Those are competitive pressures banks can absorb. The existential threat is technology that eliminates the need for banks as the settlement layer between transactions.", duration: 10.0 },
        { text: "When you can transfer value directly, instantly, without intermediaries... the bank doesn't become inefficient. It becomes unnecessary.", duration: 7.1 },
        { text: "And the infrastructure enabling this elimination isn't theoretical. It's already operational. The countdown has already begun.", duration: 6.7 },
    ],
    6: [
        { text: "Every single time you tap your phone at a coffee shop, every Venmo transfer to your roommate, every 'instant' payment through whatever flashy fintech app just launched—it all flows through the same ancient plumbing.", duration: 10.0 },
        { text: "The banks built the pipes. And they never let go. When credit cards emerged, the Big Five didn't panic. They bought in.", duration: 8.0 },
        { text: "When online banking threatened branch networks, they digitized faster than anyone expected. When PayPal and Square and Stripe promised to revolutionize payments, the banks smiled and collected their interchange fees anyway.", duration: 10.0 },
        { text: "Because here's what most people don't understand: disruption in banking is an illusion. The settlement layer—where money actually moves from one place to another—that's still controlled by the same institutions.", duration: 10.0 },
        { text: "Fintech didn't replace banks. It built prettier interfaces on top of bank infrastructure. It's like thinking you've disrupted the postal service because you designed a nicer mailbox.", duration: 9.8 },
        { text: "The Big Five survived every wave of innovation for one simple reason: they own the rails. They are the rails.", duration: 7.3 },
        { text: "But what happens when someone builds entirely new rails? That's where this story takes a dark turn.", duration: 6.2 },
        { text: "That's where this story takes a dark turn.", duration: 6.0 },
    ],
    7: [
        { text: "Here's the thing about technological disruption. It doesn't compete with the old system. It makes the old system invisible.", duration: 7.1 },
        { text: "When you send money today, it passes through a labyrinth. Your bank talks to a correspondent bank, which talks to a clearinghouse, which talks to another correspondent bank, which finally reaches the destination.", duration: 10.0 },
        { text: "Two to three days. Fees extracted at every single checkpoint. And you never see any of it.", duration: 6.4 },
        { text: "Now picture something different. You hold digital dollars. Your recipient holds a wallet. You send. They receive. Seconds later, it's done.", duration: 7.9 },
        { text: "No intermediaries. No correspondent banks. No clearinghouses taking their cut. The transaction exists on a shared ledger that neither of you controls, but both of you can verify.", duration: 10.0 },
        { text: "This is what stablecoin settlement actually looks like. And it's not theoretical. It's happening right now, moving billions of dollars daily outside the traditional banking system entirely.", duration: 10.0 },
        { text: "Banks have survived every innovation by absorbing it. ATMs? They owned them. Online banking? They built it. Mobile payments? They partnered.", duration: 7.9 },
        { text: "But this is different. This isn't a better ATM. This is the ATM becoming irrelevant.", duration: 6.0 },
        { text: "And the banks? They're just starting to understand what that means.", duration: 6.0 },
    ],
    8: [
        { text: "Right now, while most Canadians sleep through this monetary revolution, forty thousand of their neighbors are already living in it.", duration: 7.9 },
        { text: "This isn't some whitepaper fantasy. This is happening in three provinces simultaneously.", duration: 6.0 },
        { text: "In Alberta, credit unions have partnered with blockchain infrastructure to test CAD-pegged stablecoins for everyday transactions.", duration: 6.3 },
        { text: "Members are paying for groceries, settling debts, transferring funds—all without touching the traditional banking rails.", duration: 6.0 },
        { text: "Ontario launched its pilot six months ago. British Columbia followed eight weeks later. Forty thousand users. Real accounts. Real money.", duration: 7.9 },
        { text: "Real transactions flowing through systems that bypass everything we thought we knew about Canadian banking.", duration: 6.0 },
        { text: "These aren't crypto enthusiasts or tech evangelists. These are teachers, nurses, contractors—ordinary people who applied for pilot programs.", duration: 7.1 },
        { text: "The credit unions running these tests aren't advertising them. The banks they threaten aren't acknowledging them. And the regulators watching from the sidelines?", duration: 9.1 },
        { text: "They're taking notes while pretending this changes nothing. But here's what the internal documents reveal about these pilots that nobody was supposed to see.", duration: 9.5 },
    ],
    9: [
        { text: "Let me show you exactly why banking executives are losing sleep. Wire transfer. Your bank charges thirty dollars, sometimes more. The protocol? Two cents.", duration: 8.7 },
        { text: "Not two dollars. Two pennies. Savings yield. Your bank offers half a percent if you're lucky. The protocol delivers four and a half percent.", duration: 8.7 },
        { text: "That's nine times the return on your money. Now look at credit. Banks charge prime plus two percent, sometimes higher. The decentralized rate?", duration: 8.3 },
        { text: "Two full points below their best offer. These aren't projections. These aren't marketing promises. These are the actual rates pilot users are accessing right now.", duration: 9.0 },
        { text: "Today, while you're watching this. The math is devastating. On a hundred thousand dollar balance, you'd earn four thousand more per year. On a mortgage,", duration: 9.0 },
        { text: "you'd save tens of thousands over the life of the loan. Banks physically cannot compete with these numbers. Their overhead alone—the buildings, the executives,", duration: 8.7 },
        { text: "the shareholders demanding returns—makes matching these rates impossible. It's not about better technology. It's about a fundamentally broken cost structure that's been hidden from you", duration: 9.0 },
        { text: "for decades. And that structure is about to collapse. Banks physically cannot compete with these numbers. Their overhead alone makes matching these rates impossible. The structure is collapsing now.", duration: 10.0 },
    ],
    10: [
        { text: "The numbers don't lie, and neither does this internal cost analysis that was never meant to see daylight.", duration: 7.0 },
        { text: "Four hundred and twenty dollars. That's what traditional banks spend per customer, per year, just to keep the lights on.", duration: 7.8 },
        { text: "Legacy infrastructure built in the nineteen eighties. Compliance departments that have tripled in size since 2008. Physical branches bleeding cash in an increasingly digital world.", duration: 9.7 },
        { text: "Now here's what makes this devastating. Fintech competitors operate at roughly sixty dollars per customer annually. That's a seven-to-one cost disadvantage before banks even think about competing.", duration: 10.0 },
        { text: "And banks aren't greedy villains here. They're trapped. Trapped in an outdated cost structure they cannot escape without dismantling everything they've built.", duration: 8.5 },
        { text: "You can't simply delete forty years of accumulated systems and regulations overnight. The internal memo from one of America's largest regional banks put it bluntly.", duration: 9.7 },
        { text: "Quote: No competitive response identified. End quote. They've done the math. They know what's coming. And their own analysis says they have no answer.", duration: 9.3 },
        { text: "So what happens when an industry admits, in writing, that it cannot compete? We found out exactly what their contingency plan looks like.", duration: 8.9 },
        { text: "Return JSON with segments array. Each segment has text and image_prompt.", duration: 6.0 },
    ],
    11: [
        { text: "While Canada shields its banking oligopoly from disruption, Sweden took the opposite path—and the results are measurable.", duration: 7.2 },
        { text: "In 2012, Swedish banks launched Swish, a real-time payment system now used by over eighty percent of the population.", duration: 8.0 },
        { text: "Bank branches didn't just decline—they collapsed. From two thousand locations to under one thousand in a decade.", duration: 7.2 },
        { text: "Transaction fees that once bled consumers dry? Virtually eliminated for everyday payments. The average Swedish household saves hundreds annually on banking costs.", duration: 9.3 },
        { text: "But here's what the innovation cheerleaders won't tell you. Sweden's transition wasn't painless. The rapid shift left elderly citizens stranded.", duration: 8.4 },
        { text: "Some couldn't buy groceries because cash acceptance vanished faster than alternatives appeared. Privacy advocates raised alarms as every transaction became trackable.", duration: 8.8 },
        { text: "And during the rollout, system outages left millions temporarily locked out of their own money. Sweden accepted these tradeoffs.", duration: 8.0 },
        { text: "They decided short-term disruption was worth long-term efficiency. Canada made the opposite choice—protecting stability and incumbent profits over consumer benefit.", duration: 8.4 },
        { text: "Neither path is objectively correct. But only one country was honest about the choice being made.", duration: 6.7 },
    ],
    12: [
        { text: "Forty thousand users sounds small. Insignificant, even. A rounding error in a nation of forty million people.", duration: 6.8 },
        { text: "But here's what the banks are desperately hoping you don't understand: technology adoption doesn't grow linearly. It grows exponentially once it crosses what researchers call the social proof threshold.", duration: 10.0 },
        { text: "Look at the pattern. The internet took decades to reach its first fifty million users. Then it exploded. Smartphones followed the same curve.", duration: 9.2 },
        { text: "Facebook. TikTok. Every transformative technology shows identical behavior—slow, slow, slow, then vertical.", duration: 6.0 },
        { text: "The critical mass for financial technology in a developed economy sits between three and five percent of the adult population. In Canada, that translates to roughly one and a half to two million active users.", duration: 10.0 },
        { text: "Once you cross that line, network effects take over. Every new user makes the platform more valuable for existing users.", duration: 8.0 },
        { text: "Merchants start accepting it because customers demand it. Customers join because merchants accept it. The flywheel becomes self-sustaining.", duration: 7.2 },
        { text: "Forty thousand today. Four hundred thousand in eighteen months. Two million by late twenty-twenty-six.", duration: 6.0 },
        { text: "The math isn't speculation. It's the same curve that destroyed Blockbuster, Kodak, and taxi medallions.", duration: 6.0 },
    ],
    13: [
        { text: "Here's the thing about bank runs in 2023: they don't start in headlines. They start in hashtags.", duration: 6.7 },
        { text: "Our analysis points to something banks fundamentally cannot counter: viral frustration. The tipping point won't come from some fintech marketing campaign.", duration: 8.2 },
        { text: "It'll come from a twenty-three-year-old in Austin showing her phone screen. Zero point zero two dollars. That's her transfer. Instant. Done.", duration: 8.2 },
        { text: "Then she shows the yield. Four point five percent. Exposed against her Chase savings rate of zero point zero one.", duration: 7.9 },
        { text: "That video gets eighteen million views in forty-eight hours. TikTok has already fundamentally rewired how an entire generation makes financial decisions.", duration: 8.2 },
        { text: "They don't call advisors. They don't read prospectuses. They watch someone their age do the thing, and they copy it.", duration: 7.9 },
        { text: "Financial FOMO is real, and it moves faster than any institution can respond to. Banks operate on quarterly planning cycles.", duration: 7.9 },
        { text: "Social media operates on hourly trend cycles. When hashtag Ditch Your Bank starts trending, compliance teams will still be drafting their response memo.", duration: 9.0 },
        { text: "The asymmetry is devastating. Traditional banking cannot respond to viral adoption at social media speed. And that's exactly what makes this scenario so dangerous.", duration: 9.4 },
    ],
    14: [
        { text: "Two point three million Canadians. Six weeks. That's not a projection pulled from thin air—that's the mathematical model sitting in three separate bank risk departments right now.", duration: 10.0 },
        { text: "Here's how it unfolds. Week one: early adopters—the crypto-native crowd, the financially sophisticated—they move first. They post their yield screenshots.", duration: 8.3 },
        { text: "Four percent. Five percent. Numbers their followers have never seen from a savings account.", duration: 6.0 },
        { text: "Week two: the algorithm notices. Engagement spikes. Financial influencers smell content. They pile on.", duration: 6.0 },
        { text: "Week three: mainstream media can't ignore it anymore. Headlines shift from curiosity to alarm. 'Are Canadians abandoning traditional banks?'", duration: 7.9 },
        { text: "Week four: your coworker mentions it at lunch. Your neighbor asks if you've heard about it. The conversation crosses from online to kitchen tables.", duration: 10.0 },
        { text: "Weeks five and six: critical mass. Fear of missing out becomes indistinguishable from genuine financial strategy. The movement feeds itself.", duration: 8.3 },
        { text: "But here's what makes this different from every bank panic in history. People aren't running away from danger. They're running toward something better.", duration: 9.6 },
        { text: "This isn't a bank run from fear. It's a bank run toward opportunity.", duration: 6.0 },
    ],
    15: [
        { text: "When deposits flee at this velocity, bank stocks don't decline—they crater.", duration: 6.0 },
        { text: "During the 2023 regional banking crisis, First Republic lost ninety percent of its value in sixty days.", duration: 7.4 },
        { text: "Silicon Valley Bank collapsed in forty-eight hours. Signature Bank—gone overnight.", duration: 6.0 },
        { text: "And those were regional players. Now apply that contagion to Canada's Big Five.", duration: 6.0 },
        { text: "TD Bank. Royal Bank. BMO. Scotiabank. CIBC. Combined market capitalization exceeding six hundred billion dollars.", duration: 6.5 },
        { text: "These institutions anchor retirement portfolios, pension funds, index funds across the country.", duration: 6.0 },
        { text: "A forty percent correction—which is modest by crisis standards—erases two hundred forty billion dollars in shareholder value.", duration: 7.4 },
        { text: "Not over years. Over weeks. Potentially days. Your RRSP. Your company pension. Your index ETF.", duration: 6.5 },
        { text: "All hold significant positions in these five banks. They're considered safe. Blue chip. Too big to fail.", duration: 7.4 },
        { text: "But too big to fail doesn't mean too big to fall. It means taxpayers absorb the damage when they do. The 2008 playbook proved that.", duration: 10.0 },
    ],
    16: [
        { text: "When the dominoes start falling, the government faces an impossible trilemma.", duration: 6.0 },
        { text: "Option one: bail out the banks. Protect the oligopoly that's served them for decades. But after 2008, after every broken promise about too big to fail,", duration: 10.0 },
        { text: "the public won't forgive another taxpayer-funded rescue. Trust in institutions—already at historic lows—collapses entirely.", duration: 6.1 },
        { text: "Option two: let market forces do their work. Allow failing banks to fail. Sounds principled until you realize eighty thousand jobs vanish overnight.", duration: 10.0 },
        { text: "Mortgages freeze. Small businesses lose credit lines. The economic contagion spreads faster than any policy response can contain.", duration: 7.8 },
        { text: "Option three: find some middle path. Partial intervention. Selective support. But who decides which banks survive? Which communities get sacrificed?", duration: 8.7 },
        { text: "Every choice creates winners and losers—and enemies. Here's what makes this moment different from every previous crisis. Social media means the government can't control the narrative.", duration: 10.0 },
        { text: "Bank runs happen at the speed of Twitter. And international markets don't wait for parliamentary debates. The window for decision-making isn't weeks. It isn't days.", duration: 10.0 },
        { text: "It's maybe seventy-two hours before markets force their hand.", duration: 6.0 },
    ],
    17: [
        { text: "The most likely outcome isn't collapse or revolution—it's compromise through emergency legislation.", duration: 6.0 },
        { text: "Our analysis of draft proposals already circulating in Brussels and Washington reveals the playbook: mandatory banking licenses for decentralized protocols,", duration: 9.0 },
        { text: "KYC requirements embedded at the wallet level, transaction reporting thresholds that make privacy functionally illegal.", duration: 6.7 },
        { text: "This creates friction. Massive friction. Adoption timelines that measured in months now stretch to years.", duration: 6.7 },
        { text: "Compliance costs eliminate smaller players. Innovation migrates to friendlier jurisdictions.", duration: 6.0 },
        { text: "But here's what regulators consistently fail to understand: friction is not prevention.", duration: 6.0 },
        { text: "Remember taxi medallions? Cities created artificial scarcity, licensing requirements, insurance mandates—every barrier imaginable. Uber arrived anyway.", duration: 7.2 },
        { text: "Within a decade, the medallion system that took seventy years to build became worthless.", duration: 6.3 },
        { text: "The parallel is precise. Regulatory frameworks assume centralized points of control. Decentralized systems route around them by design.", duration: 8.1 },
        { text: "You can slow the water, but you cannot make it flow uphill permanently. Every month of delay costs traditional banks market share they will never recover. The legislation buys time—perhaps eighteen months, perhaps three years. It does not buy survival.", duration: 10.0 },
    ],
    18: [
        { text: "By 2029, TD Bank still exists. So does RBC. Their logos still glow on street corners across Canada.", duration: 7.5 },
        { text: "But something fundamental has changed. These institutions no longer control the financial infrastructure. They've become interface layers—user-friendly portals built on top of public payment rails.", duration: 10.0 },
        { text: "Think about what happened to telecom companies. AT&T once owned communication itself. They controlled every call, every connection, every penny that flowed through human conversation.", duration: 10.0 },
        { text: "Today, they're pipes. Dumb pipes carrying WhatsApp messages and Zoom calls built by companies that didn't exist when AT&T ruled.", duration: 8.3 },
        { text: "The same transformation is coming for banking. The leaked transition documents reveal the end state: banks competing on customer experience, not infrastructure control.", duration: 9.5 },
        { text: "They'll offer budgeting tools, financial advice, premium features. What they won't offer is exclusive access to moving your own money.", duration: 8.3 },
        { text: "The thousand-dollar barrier between you and your funds? Gone. The three-day hold while they profit from your paycheck? Eliminated.", duration: 7.9 },
        { text: "Not because regulators finally acted. Not because politicians found courage. Because the technology made their monopoly obsolete.", duration: 7.0 },
        { text: "The banks saw this future in their own projections. They just hoped you wouldn't. The thousand-dollar barrier between you and your funds?", duration: 9.1 },
        { text: "Gone. The three-day hold while they profit from your paycheck? Eliminated. Every constraint that made them billions simply vanishes into instant infrastructure.", duration: 9.1 },
    ],
    19: [
        { text: "The honest truth? Decentralized finance isn't a miracle cure. Smart contracts can be exploited. Regulations remain a patchwork of confusion.", duration: 7.9 },
        { text: "And millions of elderly Canadians, rural communities without reliable internet, they could be left behind in this transition.", duration: 7.1 },
        { text: "These aren't minor concerns. They're serious obstacles that demand real solutions.", duration: 6.0 },
        { text: "But here's what the data actually shows. Canadians using decentralized platforms pay an average of sixty percent less in transaction fees.", duration: 8.2 },
        { text: "Savings accounts on these protocols yield eight to twelve percent annually, compared to the one percent your bank generously offers.", duration: 7.9 },
        { text: "And for the first time in decades, genuine competition is forcing legacy institutions to improve.", duration: 6.0 },
        { text: "The choice was never between a perfect system and a flawed one. That fantasy doesn't exist.", duration: 6.3 },
        { text: "The real choice is between a century-old monopoly that's quietly extracted billions from your family, and an evolving alternative that, despite its growing pains, returns power to individual Canadians.", duration: 10.0 },
        { text: "Status quo feels safe because it's familiar. But familiar isn't the same as secure. The banking system you trust has already decided you're the product, not the customer.", duration: 10.0 },
    ],
    20: [
        { text: "Those encrypted documents I mentioned at the beginning of this video? I've saved the most revealing line for last.", duration: 7.3 },
        { text: "It wasn't about blockchain technology. It wasn't about competitive pressure from fintech startups. It wasn't even about the regulatory failures we've discussed.", duration: 8.5 },
        { text: "It was this single sentence, buried on page forty-seven of an internal strategy memo: Timeline to significant disruption: eighteen to twenty-four months.", duration: 8.5 },
        { text: "They wrote that fourteen months ago. The executives at these institutions have known exactly what's coming.", duration: 6.2 },
        { text: "They've been positioning themselves accordingly, quietly moving assets, restructuring portfolios, preparing exit strategies while publicly insisting everything is fine.", duration: 7.3 },
        { text: "Now you know too. You've seen the debt structures they don't advertise. You understand the derivative exposure they minimize in quarterly reports.", duration: 8.5 },
        { text: "You recognize the warning signs they're trained to dismiss. The transformation we've outlined isn't a possibility anymore. It's a countdown.", duration: 7.7 },
        { text: "The only question that matters now is this: which side of this transition will you be on? The side that saw it coming and prepared?", duration: 9.6 },
        { text: "Or the side that trusted the same institutions that created this mess in the first place? The clock is running.", duration: 7.7 },
    ],
};
