// Auto-generated segment data from Airtable
// Video: The AI Bubble's NEXT Victim: Cloud Computing's $300B Collapse
// Generated for word-to-image alignment in Remotion

export interface SegmentText {
    text: string;
    duration: number;
}

export const sceneSegmentData: Record<number, SegmentText[]> = {
    1: [
        { text: "You thought the AI bubble was bad? The cloud computing industry just realized they built a three hundred billion dollar empire on quicksand.", duration: 8.8 },
        { text: "And when this falls, it's taking your Netflix subscription, your company's entire infrastructure, and possibly the internet itself with it.", duration: 7.6 },
        { text: "Here's the financial time bomb nobody's talking about. Right now, three companies control nearly two-thirds of the world's cloud infrastructure.", duration: 7.6 },
        { text: "Amazon, Microsoft, and Google. They convinced every business on Earth to abandon their own servers and rent digital space instead. Seemed genius.", duration: 8.4 },
        { text: "Until the math stopped working. These hyperscalers have been hemorrhaging cash building AI data centers, betting everything on artificial intelligence revenue that hasn't materialized.", duration: 9.1 },
        { text: "Meanwhile, their core cloud customers are waking up to a brutal reality: they're trapped in contracts they can't afford, dependent on infrastructure they don't control.", duration: 9.5 },
        { text: "With no exit strategy. The warning signs are everywhere if you know where to look. Earnings reports buried in creative accounting.", duration: 8 },
        { text: "Capacity utilization numbers that don't add up. And a pricing war that's destroying margins industry-wide. What happens when the companies hosting civilization's data start cutting corners?", duration: 9.9 },
        { text: "We're about to find out.", duration: 6 },
    ],
    2: [
        { text: "Every time you stream a movie, send money through Venmo, or have your medical records pulled up at a hospital, you're pinging one of three companies.", duration: 10 },
        { text: "Amazon Web Services, Microsoft Azure, and Google Cloud don't just dominate the market. They are the market. Sixty-five percent of every digital interaction on Earth flows through their servers.", duration: 10 },
        { text: "Netflix? AWS. Most major banks? Azure. The startup handling your prescription refills? Probably Google Cloud.", duration: 6 },
        { text: "This isn't some abstract financial story about shareholders losing money. This is about the actual infrastructure holding modern life together.", duration: 7.8 },
        { text: "When these platforms hiccup, airlines ground flights. When they go down, emergency services lose communication. When they struggle financially, they don't just cut jobs—they cut capacity.", duration: 10 },
        { text: "And right now, all three are hemorrhaging cash trying to win an AI arms race nobody asked them to fight.", duration: 7.8 },
        { text: "They've bet hundreds of billions that artificial intelligence will justify every dollar spent. But what happens when those bets don't pay off?", duration: 8.6 },
        { text: "What happens when the companies running civilization's backbone can't afford to keep the lights on?", duration: 6 },
    ],
    3: [
        { text: "The question nobody in Silicon Valley wants to answer is deceptively simple. How did the most sophisticated financial minds on the planet construct a business model built on the same circular financing schemes", duration: 10 },
        { text: "that destroyed Enron and triggered the 2008 global meltdown? The answer lives in three words that should terrify every investor holding cloud computing stock: compute credit deals.", duration: 10 },
        { text: "Here's what the earnings calls won't tell you. When a major cloud provider reports billions in new AI revenue, a significant portion isn't coming from customers paying cash.", duration: 10 },
        { text: "It's coming from startups spending credits that the cloud provider itself funded through venture investments. The money goes out one door as an investment, walks around the block,", duration: 10 },
        { text: "and comes back in the other door disguised as revenue. Enron called these 'prepay transactions.' Banks in 2007 called them 'structured investment vehicles.' Today, they're called 'strategic cloud partnerships.'", duration: 10 },
        { text: "Different decade. Different industry. Identical accounting sleight of hand. The documents tell a story that the press releases carefully obscure. And once you see the pattern,", duration: 9.7 },
        { text: "you cannot unsee it.", duration: 6 },
        { text: "you cannot unsee it.", duration: 6 },
    ],
    4: [
        { text: "Here's the dirty secret Wall Street doesn't want you to understand. These aren't investments. They're accounting tricks dressed up as billion-dollar bets.", duration: 8.3 },
        { text: "Amazon hands Anthropic four billion dollars. Sounds impressive, right? But here's the catch—Anthropic must spend that exact amount on Amazon's cloud services.", duration: 8.3 },
        { text: "The money never really leaves Amazon's ecosystem. It's a round trip disguised as a partnership.", duration: 6 },
        { text: "Microsoft plays the same game, only bigger. Thirteen billion into OpenAI. But OpenAI burns through that cash exclusively on Azure servers.", duration: 7.9 },
        { text: "Microsoft books it as cloud revenue, then reports record growth to shareholders.", duration: 6 },
        { text: "Follow the money. It flows in a perfect circle. Investment out, cloud fees back in, revenue reported, stock price climbs, more investment announced.", duration: 8.6 },
        { text: "This isn't venture capital. This is vendor financing with extra steps. The cloud giants have trapped themselves in a codependent spiral with companies that have never turned a profit.", duration: 10 },
        { text: "They're simultaneously the bank, the landlord, and the biggest customer. When your investment thesis requires your investment target to pay you back through service fees, you haven't made a bet on the future.", duration: 10 },
        { text: "You've created a financial hall of mirrors.", duration: 6 },
    ],
    5: [
        { text: "Twenty-three years ago, Enron executives sat in Houston boardrooms, engineering the most sophisticated financial illusion in corporate history.", duration: 7.6 },
        { text: "Their weapon? Special Purpose Entities. Shell companies designed to hide debt while booking phantom revenue.", duration: 6.3 },
        { text: "They'd sell assets to subsidiaries they secretly controlled, then record the sales as profit. The money moved in circles, but the balance sheet looked immaculate.", duration: 10 },
        { text: "Arthur Andersen signed off on everything. Technically legal, they said. Innovative accounting.", duration: 6 },
        { text: "We know how that ended. Now look at today's cloud AI deals. Company A invests two billion in a startup.", duration: 8.4 },
        { text: "That startup commits to spending two billion on Company A's cloud services. Revenue appears. Stock prices climb. Everyone celebrates.", duration: 8 },
        { text: "The structure is nearly identical. Money cycling through related parties. Future commitments booked as present-day wins. Auditors calling it compliant.", duration: 8.4 },
        { text: "Enron's collapse erased seventy-four billion dollars in shareholder value. Employees lost everything. The warning signs were buried in footnotes nobody read.", duration: 8.8 },
        { text: "The cloud giants' footnotes tell the same story, if you know where to look. History doesn't repeat, but it rhymes with devastating precision.", duration: 9.6 },
    ],
    6: [
        { text: "Here's the thing Wall Street doesn't want you to understand. When Amazon Web Services hands a startup one hundred million dollars in compute credits, they're not being generous.", duration: 10 },
        { text: "They're running the most sophisticated revenue scheme in corporate history. Watch how the money flows. AWS issues credits to a promising AI company.", duration: 9.6 },
        { text: "That startup immediately spends those credits on Amazon's servers. And here's where the magic happens. AWS records that spending as genuine revenue in their quarterly earnings.", duration: 10 },
        { text: "But wait. Where did the actual cash come from? It came from venture capitalists who funded the startup. The same venture capitalists who invested because they saw AWS backing the company.", duration: 10 },
        { text: "It's a closed loop. Investment dollars get laundered through compute credits and emerge as revenue growth. Amazon's own promotional documentation reveals the structure. Credits expire. They're non-transferable.", duration: 10 },
        { text: "They exist purely within Amazon's ecosystem. This isn't commerce. It's accounting alchemy. The startup gets runway. AWS gets revenue recognition. Investors see growth metrics.", duration: 10 },
        { text: "Everyone wins. Until the music stops and someone asks the obvious question: who's actually paying for all this infrastructure?", duration: 7.9 },
        { text: "The same venture capitalists who invested because they saw AWS backing the company with credits. Investment dollars get laundered through compute credits and emerge as revenue growth on the other side.", duration: 10 },
        { text: "This isn't commerce. It's accounting alchemy turning investment into revenue without real transactions. The illusion works perfectly until someone looks behind the curtain and sees the emperor has no clothes.", duration: 10 },
    ],
    7: [
        { text: "Here's what Amazon doesn't want you to understand about their Anthropic deal. In September 2023, Amazon invested four billion dollars into Anthropic.", duration: 8.6 },
        { text: "That's real cash leaving Amazon's treasury. But here's where it gets interesting. As part of that investment, Anthropic committed to spending four billion dollars on Amazon Web Services.", duration: 10 },
        { text: "Follow the money. Amazon writes a four billion dollar check to Anthropic. Anthropic turns around and writes that same money back to Amazon's cloud division.", duration: 9.7 },
        { text: "AWS then reports this as revenue growth. Wall Street celebrates. Stock price climbs. But wait. Those are the same dollars.", duration: 7.8 },
        { text: "Amazon essentially paid itself and called it growth. The cash made a round trip. Out of Amazon's corporate treasury, into Anthropic's bank account, straight back into AWS.", duration: 10 },
        { text: "One pile of money, counted twice on the balance sheet. Once as a strategic investment. Once as organic cloud revenue.", duration: 7.8 },
        { text: "This isn't illegal. It's technically within accounting rules. But it fundamentally distorts what investors think they're seeing when they look at cloud growth numbers.", duration: 9.3 },
        { text: "And Amazon isn't alone in this practice.", duration: 6 },
        { text: "Those are the same dollars.", duration: 6 },
    ],
    8: [
        { text: "Here's the time bomb Wall Street doesn't want you to see. When a cloud provider builds a fifty billion dollar data center, they don't record that as an immediate expense.", duration: 10 },
        { text: "They spread it out. Depreciate it over ten years. That means their books show just five billion in annual costs. Nice, clean, predictable.", duration: 8.1 },
        { text: "But here's the problem. GPU technology doesn't last ten years. It becomes obsolete in eighteen to twenty-four months. That shiny new AI chip you just paid a premium for?", duration: 10 },
        { text: "It's already being replaced by something twice as powerful. So what happens to that fifty billion dollar facility when the hardware inside it is worthless in two years?", duration: 9.8 },
        { text: "The math is brutal. If you've only depreciated ten billion over two years, but you need to replace everything now, you're sitting on forty billion dollars in assets that are", duration: 10 },
        { text: "suddenly worth a fraction of their book value. That's not a write-down. That's a detonation. And this isn't one company's problem. Every major cloud provider is running the", duration: 9.8 },
        { text: "same playbook. The same aggressive depreciation schedules. The same assumptions that technology won't leapfrog their infrastructure. The accelerated write-downs are coming.", duration: 7.4 },
        { text: "The accelerated write-downs are coming.", duration: 6 },
    ],
    9: [
        { text: "Here's the terrifying math Wall Street doesn't want you to see.", duration: 6 },
        { text: "Buried in financial footnotes, not press releases, are binding purchase commitments that could bankrupt the cloud industry.", duration: 7.6 },
        { text: "Microsoft has committed to forty-four billion dollars in future chip purchases. Amazon's obligations exceed fifty billion. Google, another thirty-eight billion.", duration: 9 },
        { text: "These aren't projections. These are legally binding contracts, primarily with one company: NVIDIA.", duration: 6 },
        { text: "The hyperscalers made these commitments when AI demand seemed infinite. They locked in prices. They guaranteed volumes.", duration: 7.6 },
        { text: "They signed multi-year agreements that cannot be cancelled without catastrophic penalties.", duration: 6 },
        { text: "Now consider what happens if enterprise AI adoption slows by even twenty percent.", duration: 6 },
        { text: "These companies must still purchase chips they cannot deploy profitably. They've essentially bet their entire capital expenditure strategy on AI demand accelerating indefinitely.", duration: 10 },
        { text: "NVIDIA's own filings reveal the concentration of risk. The top four cloud providers represent over forty percent of their data center revenue.", duration: 9.9 },
        { text: "If the AI bubble deflates, these purchase commitments become anchors dragging the entire cloud industry underwater.", duration: 7.2 },
    ],
    10: [
        { text: "The year was 2008, and Wall Street had performed the greatest magic trick in financial history. They took worthless mortgages, sliced them into tranches, scattered them across the global economy.", duration: 10 },
        { text: "And convinced everyone the risk had simply... vanished. It hadn't vanished. It had metastasized.", duration: 6 },
        { text: "Today, Silicon Valley has perfected the same illusion with different instruments.", duration: 6 },
        { text: "Follow the money. Microsoft invests thirteen billion in OpenAI. OpenAI spends billions on Microsoft Azure. Amazon backs Anthropic. Anthropic pays Amazon Web Services.", duration: 9.6 },
        { text: "Google funds AI startups who rent Google Cloud infrastructure. It's a carousel of capital where everyone owes everyone, and nobody can trace where actual value creation occurs.", duration: 10 },
        { text: "The cloud providers count AI spending as revenue. The AI companies count cloud investments as validation. The venture capitalists count both as proof the party never ends.", duration: 10 },
        { text: "But here's what the 2008 crisis taught us: circular dependencies don't create stability. They create synchronized failure.", duration: 7.1 },
        { text: "When Lehman collapsed, institutions discovered they were all holding pieces of the same rotting assets.", duration: 6.2 },
        { text: "The cloud ecosystem has built an identical trap, just with server racks instead of subprime loans.", duration: 6.7 },
    ],
    11: [
        { text: "Now let's untangle the most Byzantine financial arrangement in tech history. Microsoft invested thirteen billion dollars into OpenAI.", duration: 7.7 },
        { text: "In return, OpenAI runs exclusively on Azure, Microsoft's cloud platform. Here's where it gets interesting. When OpenAI pays Microsoft for cloud computing,", duration: 9.4 },
        { text: "Microsoft books that as revenue. They're essentially paying themselves with their own investment money and calling it growth.", duration: 7.7 },
        { text: "But wait, there's more. Microsoft also receives seventy-five percent of OpenAI's profits until that thirteen billion is fully repaid.", duration: 8.1 },
        { text: "The problem? OpenAI has never turned a profit. They're burning through capital faster than they can raise it.", duration: 7.7 },
        { text: "Yet somehow, OpenAI carries a one hundred fifty billion dollar valuation. A company with negative cash flow, completely dependent on a single customer", duration: 9.8 },
        { text: "who is also its primary investor and infrastructure provider. The circular logic is staggering. Microsoft's AI revenue depends on OpenAI's success.", duration: 8.9 },
        { text: "OpenAI's survival depends on Microsoft's continued funding. Neither can fail without destroying the other. This isn't a partnership.", duration: 7.7 },
        { text: "It's a financial house of cards where both parties are simultaneously holding it up and leaning on it for support.", duration: 8.5 },
    ],
    12: [
        { text: "Here's the math that should terrify every investor in this space. AI startups backed by hyperscalers are collectively burning through twenty billion dollars annually—just on compute costs alone.", duration: 10 },
        { text: "Not salaries. Not marketing. Just keeping the servers running. And here's what nobody wants to talk about: most of these companies have absolutely no realistic path to profitability.", duration: 10 },
        { text: "None. They're buying time, not building businesses. The average AI startup right now has eighteen to twenty-four months of runway remaining. Look at that number again.", duration: 10 },
        { text: "Eighteen to twenty-four months. Now remember what we said about GPU obsolescence cycles? They're identical. This isn't coincidence—it's synchronized detonation timing.", duration: 8.6 },
        { text: "These companies will need to replace their entire compute infrastructure at the exact moment their funding runs dry. They'll approach investors for more capital while simultaneously admitting their core technology is already outdated.", duration: 10 },
        { text: "The burn rate charts tell the story plainly. Cash reserves declining at forty, fifty, sixty percent annually. Runway projections converging toward zero.", duration: 9 },
        { text: "And every month, the price of staying competitive increases while the window for profitability shrinks.", duration: 6.1 },
        { text: "The fuse is already lit.", duration: 6 },
        { text: "The only question is who runs out of money first.", duration: 6 },
    ],
    13: [
        { text: "The accounting magic happens in plain sight. When a cloud provider extends a hundred million in credits to a startup, that startup immediately spends those credits on cloud services.", duration: 10 },
        { text: "Under Generally Accepted Accounting Principles, this books as legitimate revenue the moment the service is delivered. The auditors sign off because technically, two separate legal entities engaged in an arm's length transaction.", duration: 10 },
        { text: "But follow the money. It starts in the cloud provider's treasury, moves briefly through the startup's account, then flows right back as payment for services.", duration: 9.4 },
        { text: "The provider's revenue line swells. Their cash position barely changes. Wall Street celebrates the growth. This isn't fraud. That's what makes it so dangerous.", duration: 9 },
        { text: "Every transaction meets the letter of accounting law. Revenue recognition rules require only that a service was provided and a customer agreed to pay.", duration: 9 },
        { text: "They don't ask whether that customer's ability to pay originated from the vendor itself. It's a closed loop disguised as commerce.", duration: 7.9 },
        { text: "The provider is essentially paying itself, booking the payment as income, and reporting it to shareholders as organic growth.", duration: 7.1 },
        { text: "The Big Four auditors approve these financials every quarter. The system validates the illusion because the mechanics are technically compliant.", duration: 7.5 },
        { text: "Wall Street doesn't distinguish between revenue that cycled through a customer and revenue that simply returned home. The quarterly earnings call treats both as victory.", duration: 9.4 },
    ],
    14: [
        { text: "Google isn't just playing catch-up. They're gambling everything. As the third-place hyperscaler, Google Cloud has been hemorrhaging cash to win AI customers.", duration: 9.2 },
        { text: "Their strategy? Outspend everyone. Longer contract terms. More generous credits. Sweeter deals than AWS or Azure would ever offer.", duration: 7.9 },
        { text: "And it's working—on paper. Google Cloud's AI revenue has exploded, growing faster than either competitor. Wall Street celebrated. Analysts upgraded the stock.", duration: 9.2 },
        { text: "But here's what they're not telling you. Google's parent company Alphabet has invested billions in Anthropic—the same AI startup that Amazon is also backing.", duration: 10 },
        { text: "Think about that. Google is funding a company that competes with its own AI offerings while simultaneously giving that company's rivals free cloud credits.", duration: 10 },
        { text: "The circular exposure is staggering. When you strip away the promotional credits, when you account for the deferred revenue, when you examine the actual cash changing hands—", duration: 10 },
        { text: "Google Cloud's AI growth looks increasingly artificial. They're not building a sustainable business. They're buying market share with shareholder money, hoping the music never stops.", duration: 10 },
        { text: "And Alphabet's leadership knows something we don't. Because insider selling has quietly accelerated over the past six months.", duration: 7.5 },
        { text: "Return JSON with segments array. Each segment has text and image_prompt.", duration: 6 },
    ],
    15: [
        { text: "Here's how it starts. One name. One headline. One domino. A major AI company—let's call it a billion-dollar unicorn—misses projections badly.", duration: 8.5 },
        { text: "Burns through its runway. Announces it's cutting seventy percent of its cloud compute. The provider holding three hundred million in credits takes the write-off.", duration: 9.7 },
        { text: "Stock drops eight percent overnight. Now Wall Street wakes up. Analysts start asking questions. How many other arrangements look like this? How much phantom revenue?", duration: 10 },
        { text: "Credit terms tighten within weeks. Suddenly, AI startups that relied on deferred payments face invoices they can't cover. Ten companies fold. Twenty.", duration: 8.9 },
        { text: "Each one triggers another write-off. Cloud revenue growth—the metric that justified everything—goes negative for the first time in a decade.", duration: 8.1 },
        { text: "Data centers that cost billions to build now sit at sixty percent utilization. Accountants are forced to impair assets worth tens of billions.", duration: 9.3 },
        { text: "The flywheel that powered a decade of growth? It's spinning the other direction now. Each failure accelerates the next.", duration: 7.7 },
        { text: "And the companies that bet everything on infinite AI demand? They're holding the bag.", duration: 6 },
        { text: "Each failure accelerates the next. The cascade continues, unstoppable now, feeding on its own momentum through the entire ecosystem.", duration: 7.7 },
    ],
    16: [
        { text: "The battlefield is already soaked in blood. AWS just slashed enterprise storage prices seventeen percent.", duration: 6.5 },
        { text: "Microsoft countered with twenty-two percent cuts on compute instances. Google's offering migration credits worth millions to poach clients.", duration: 7.8 },
        { text: "This isn't competition. This is desperation wearing a strategic mask. When AI workloads evaporate, three giants will suddenly find themselves hunting.", duration: 9.1 },
        { text: "The same shrinking pool of traditional enterprise customers. But here's the catastrophic math they're ignoring. These companies carry combined depreciation expenses.", duration: 9.1 },
        { text: "Exceeding ninety billion dollars annually. Those server farms don't stop costing money just because demand disappeared. Every price cut to win market share.", duration: 10 },
        { text: "Accelerates the timeline to write-downs. Wall Street models show gross margins compressing from sixty-two percent to forty-one percent within eighteen months.", duration: 9.1 },
        { text: "Of sustained price warfare. At forty-one percent margins, current infrastructure investments become permanently unprofitable. The death spiral locks in. Lower prices mean lower margins.", duration: 10 },
        { text: "Lower margins mean delayed infrastructure investment. Delayed investment means inferior service. Inferior service means customer exodus. The moat Jeff Bezos spent two decades building?", duration: 10 },
        { text: "It doesn't protect the castle anymore. It floods it. The moat has become the weapon destroying the fortress from within.", duration: 8.7 },
        { text: "The protective barrier transformed into the instrument of destruction. What was built for defense now guarantees collapse. The fortress drowns in its own defenses.", duration: 10 },
    ],
    17: [
        { text: "Here's the math Wall Street doesn't want you to see. Combined, the cloud divisions of Amazon, Microsoft, and Google carry implied valuations north of three hundred billion dollars.", duration: 10 },
        { text: "That number assumes they're high-growth tech companies riding the AI wave to infinity. But what happens when the market realizes they're actually utilities?", duration: 9.2 },
        { text: "Electric companies trade at twelve to fifteen times earnings. Telecom providers, maybe ten to fourteen. These are mature infrastructure businesses with stable but slow growth.", duration: 10 },
        { text: "Cloud computing is becoming exactly that. Apply utility multiples to these cloud divisions, and you get a very different picture.", duration: 8 },
        { text: "AWS, currently valued around one hundred billion? Cut that in half. Azure's premium valuation? Slash it by sixty percent. Google Cloud? Similar story.", duration: 9.2 },
        { text: "We're not talking about a correction. We're talking about a fundamental re-rating of what these businesses are actually worth.", duration: 7.6 },
        { text: "The total damage? Somewhere between one hundred fifty and two hundred billion dollars in market cap that simply shouldn't exist under rational valuation models.", duration: 9.6 },
        { text: "This isn't speculation. This is what happens when growth stocks mature into utilities while still wearing growth-stock price tags.", duration: 7.6 },
        { text: "The math is clear. The reckoning is coming. And when it does, the entire tech sector will feel the shockwave.", duration: 8 },
    ],
    18: [
        { text: "The numbers don't lie, but they do hide in footnotes. Here's what Wall Street isn't telling you.", duration: 7.4 },
        { text: "Start with AI customer revenue as a percentage of total cloud revenue. AWS sits at thirty-one percent.", duration: 7.4 },
        { text: "Azure hits thirty-eight percent. Google Cloud reaches a staggering forty-four percent. These aren't customers. They're dependents.", duration: 6.9 },
        { text: "Now look at disclosed compute credit liabilities. Microsoft has extended over twelve billion in credits to AI startups.", duration: 7.8 },
        { text: "Google has committed nine billion. Amazon trails at seven billion. These are IOUs that may never convert to cash.", duration: 8.2 },
        { text: "The purchase commitment footnotes reveal even more. All three have locked in GPU orders through twenty-twenty-eight, totaling over ninety billion combined.", duration: 9.1 },
        { text: "They're betting everything on demand that might evaporate. But the real scandal? Depreciation assumptions. They're writing off AI servers over six years.", duration: 9.5 },
        { text: "While the technology refreshes every eighteen months. That's aggressive accounting masking accelerated obsolescence. Azure carries the highest circular exposure, dependent on Microsoft's own AI ecosystem.", duration: 10 },
        { text: "AWS has the greatest absolute concentration of AI startup revenue. Google Cloud has extended the most credit relative to its size.", duration: 9.1 },
        { text: "This is your roadmap to understanding who falls first. The foundation is cracking, and the evidence is buried in plain sight.", duration: 9.1 },
    ],
    19: [
        { text: "The collapse won't stay contained in Silicon Valley boardrooms. When hyperscaler stocks crater, the automated systems kick in.", duration: 8 },
        { text: "Index funds rebalance. ETFs sell. Your retirement account, sitting quietly in a target-date fund, suddenly hemorrhages value because some algorithm decided.", duration: 9.4 },
        { text: "The S&P 500 is now twenty-eight percent technology. One sector's correction becomes everyone's problem. But the real damage runs deeper than portfolios.", duration: 9.8 },
        { text: "Remember that invisible infrastructure running civilization? Hospitals managing patient records. Banks processing transactions. Governments coordinating emergency services.", duration: 7.6 },
        { text: "Every enterprise customer now faces a nightmare scenario: their cloud provider is distracted, cutting costs, laying off the engineers who keep critical systems running.", duration: 10 },
        { text: "Startups built entirely on AWS discover their foundation is shaking. Payment processors. Logistics platforms. The apps coordinating modern life.", duration: 8.5 },
        { text: "This is the dependency trap we built without noticing. We concentrated civilization's digital backbone into three companies, then made those companies chase an AI dream.", duration: 10 },
        { text: "The backbone doesn't need to break completely. It just needs to become unreliable at exactly the wrong moment.", duration: 8 },
        { text: "Return to hospitals managing patient records. Banks processing transactions. The infrastructure we depend on every single day.", duration: 7.6 },
        { text: "The wrong moment approaches. And we built a system where nobody can fix it in time.", duration: 7.1 },
    ],
    20: [
        { text: "They called themselves infrastructure. As essential as electricity. As permanent as concrete. But you've seen the truth now.", duration: 6.6 },
        { text: "Three hundred billion dollars built on circular revenue, where companies pay each other to inflate growth numbers. Built on hardware they've already depreciated to zero.", duration: 9.2 },
        { text: "Built on hardware still humming in facilities that cost millions to cool. Built on AI promises that require ten times the computing power they currently possess.", duration: 9.6 },
        { text: "The cloud titans didn't build a foundation. They built a performance. And performances end. The hyperscalers will survive in some form—they always do.", duration: 8.4 },
        { text: "But the stocks trading at thirty times revenue? The pension funds betting retirement money on infinite growth? The businesses that moved everything to platforms they don't control?", duration: 9.9 },
        { text: "They're standing on quicksand. And it's already shifting. You've seen the depreciation tricks. The pricing traps. The efficiency myth. The AI spending that doesn't add up.", duration: 9.6 },
        { text: "The question was never whether this empire would crack. The question is whether you recognized the tremors in time. Because by the time quicksand reaches your waist, it's already too late.", duration: 10 },
        { text: "Because by the time quicksand reaches your waist, it's already too late to climb out. The sand is moving.", duration: 7 },
    ],
};
