import type {
  Video,
  ActivityItem,
  AnalyticsDataPoint,
  Insight,
  ScriptScene,
  StoryboardScene,
  RenderState,
  SettingsData,
  VoiceSegment,
  ImageGenItem,
  SceneVisualGroup,
} from "./types";

export const MOCK_VIDEOS: Video[] = [
  {
    id: "v1",
    title: "How Iran Fell for the Trap",
    status: "done",
    framework: "Thucydides Trap",
    videoLengthMin: 14,
    wordCount: 3520,
    sceneCount: 25,
    estimatedCost: 15.4,
    views: 98200,
    ctr: 11.2,
    retention: 68,
    watchTimeHrs: 1240,
    verdict: "hit",
    uploadDate: "2026-03-01",
    progress: 100,
    updatedAt: "2026-03-01T14:00:00Z",
  },
  {
    id: "v2",
    title: "Why the Thucydides Trap Explains Everything",
    status: "done",
    framework: "Thucydides Trap",
    videoLengthMin: 16,
    wordCount: 4010,
    sceneCount: 28,
    estimatedCost: 17.2,
    views: 145000,
    ctr: 8.7,
    retention: 72,
    watchTimeHrs: 2100,
    verdict: "hit",
    uploadDate: "2026-02-18",
    progress: 100,
    updatedAt: "2026-02-18T10:00:00Z",
  },
  {
    id: "v3",
    title: "China's $3 Trillion Dollar Trap",
    status: "rendering",
    framework: "Game Theory",
    videoLengthMin: 12,
    wordCount: 2980,
    sceneCount: 22,
    estimatedCost: 14.2,
    progress: 67,
    updatedAt: "2026-03-25T06:00:00Z",
  },
  {
    id: "v4",
    title: "The Hidden NATO Betrayal Nobody Talks About",
    status: "storyboard_review",
    framework: "Machiavelli",
    videoLengthMin: 15,
    wordCount: 3750,
    sceneCount: 26,
    estimatedCost: 16.8,
    progress: 55,
    updatedAt: "2026-03-24T19:00:00Z",
  },
  {
    id: "v5",
    title: "Japan's Economy Is a Ticking Time Bomb",
    status: "scripting",
    framework: "Sun Tzu",
    videoLengthMin: 13,
    wordCount: 3200,
    sceneCount: 24,
    estimatedCost: 14.8,
    progress: 25,
    updatedAt: "2026-03-25T02:00:00Z",
  },
  {
    id: "v6",
    title: "Why Saudi Arabia Is Secretly Terrified",
    status: "visuals",
    framework: "Game Theory",
    videoLengthMin: 11,
    wordCount: 2750,
    sceneCount: 20,
    estimatedCost: 13.5,
    progress: 42,
    updatedAt: "2026-03-24T22:00:00Z",
  },
  {
    id: "v7",
    title: "China's Rare Earth Monopoly Is Collapsing",
    status: "researching",
    framework: "Systems Thinking",
    videoLengthMin: 14,
    wordCount: 0,
    sceneCount: 0,
    estimatedCost: 0,
    progress: 10,
    updatedAt: "2026-03-25T08:00:00Z",
  },
  {
    id: "v8",
    title: "The Real Reason Russia Can't Win",
    status: "done",
    framework: "Clausewitz",
    videoLengthMin: 18,
    wordCount: 4500,
    sceneCount: 30,
    estimatedCost: 19.5,
    views: 67500,
    ctr: 5.3,
    retention: 58,
    watchTimeHrs: 890,
    verdict: "steady",
    uploadDate: "2026-03-10",
    progress: 100,
    updatedAt: "2026-03-10T14:00:00Z",
  },
  {
    id: "v9",
    title: "How Turkey Played Everyone",
    status: "done",
    framework: "Machiavelli",
    videoLengthMin: 10,
    wordCount: 2500,
    sceneCount: 18,
    estimatedCost: 11.2,
    views: 32100,
    ctr: 2.1,
    retention: 42,
    watchTimeHrs: 310,
    verdict: "underperformed",
    uploadDate: "2026-03-15",
    progress: 100,
    updatedAt: "2026-03-15T14:00:00Z",
  },
  {
    id: "v10",
    title: "India's Secret Weapon Against China",
    status: "done",
    framework: "Sun Tzu",
    videoLengthMin: 15,
    wordCount: 3800,
    sceneCount: 26,
    estimatedCost: 16.5,
    views: 112000,
    ctr: 9.4,
    retention: 65,
    watchTimeHrs: 1780,
    verdict: "hit",
    uploadDate: "2026-02-25",
    progress: 100,
    updatedAt: "2026-02-25T14:00:00Z",
  },
  {
    id: "v11",
    title: "The $50B Pipeline That Changes Everything",
    status: "voice",
    framework: "Systems Thinking",
    videoLengthMin: 12,
    wordCount: 3000,
    sceneCount: 22,
    estimatedCost: 13.8,
    progress: 35,
    updatedAt: "2026-03-24T16:00:00Z",
  },
  {
    id: "v12",
    title: "Why Africa Is the Next Superpower",
    status: "done",
    framework: "Game Theory",
    videoLengthMin: 16,
    wordCount: 4100,
    sceneCount: 28,
    estimatedCost: 18.0,
    views: 89300,
    ctr: 7.8,
    retention: 61,
    watchTimeHrs: 1450,
    verdict: "hit",
    uploadDate: "2026-02-10",
    progress: 100,
    updatedAt: "2026-02-10T14:00:00Z",
  },
];

export const MOCK_ACTIVITY: ActivityItem[] = [
  { id: "a1", message: "Script completed", timestamp: "2h ago", type: "success", videoTitle: "Japan's Economy Is a Ticking Time Bomb" },
  { id: "a2", message: "Storyboard awaiting approval", timestamp: "5h ago", type: "warning", videoTitle: "The Hidden NATO Betrayal Nobody Talks About" },
  { id: "a3", message: "New idea surfaced", timestamp: "8h ago", type: "info", videoTitle: "China's Rare Earth Monopoly Is Collapsing" },
  { id: "a4", message: "Render complete", timestamp: "12h ago", type: "success", videoTitle: "China's $3 Trillion Dollar Trap" },
  { id: "a5", message: "Voice generation started", timestamp: "14h ago", type: "info", videoTitle: "The $50B Pipeline That Changes Everything" },
  { id: "a6", message: "CTR alert: below threshold", timestamp: "1d ago", type: "error", videoTitle: "How Turkey Played Everyone" },
];

export const MOCK_ANALYTICS_DATA: AnalyticsDataPoint[] = [
  { date: "Jan", views: 15200, ctr: 4.2 },
  { date: "Feb", views: 28400, ctr: 6.8 },
  { date: "Mar", views: 22100, ctr: 5.1 },
  { date: "Apr", views: 45600, ctr: 8.3 },
  { date: "May", views: 67800, ctr: 7.2 },
  { date: "Jun", views: 89300, ctr: 9.1 },
  { date: "Jul", views: 78200, ctr: 8.5 },
  { date: "Aug", views: 95400, ctr: 10.2 },
  { date: "Sep", views: 112000, ctr: 9.8 },
  { date: "Oct", views: 98500, ctr: 8.9 },
  { date: "Nov", views: 145000, ctr: 11.2 },
  { date: "Dec", views: 128000, ctr: 10.5 },
];

export const MOCK_INSIGHTS: Insight[] = [
  {
    category: "Framework",
    title: "Thucydides Trap Dominates",
    description: "Videos using the Thucydides Trap framework average 9.95% CTR, outperforming all other frameworks by 2.4x.",
    stat: "9.95%",
    statLabel: "Avg CTR",
    color: "var(--turquoise)",
  },
  {
    category: "Thumbnail",
    title: "Red + Yellow Wins",
    description: "Thumbnails with red backgrounds and yellow text achieve 40% higher CTR than blue-toned alternatives.",
    stat: "+40%",
    statLabel: "vs Blue",
    color: "var(--gold)",
  },
  {
    category: "Length",
    title: "14-16 Min Sweet Spot",
    description: "Videos between 14-16 minutes have the highest retention rate at 68%, dropping sharply outside this range.",
    stat: "68%",
    statLabel: "Retention",
    color: "var(--orange)",
  },
];

export const MOCK_SCRIPT_SCENES: ScriptScene[] = [
  { sceneNumber: 1, actNumber: 1, narrationText: "In the shadow of a crumbling empire, one decision would reshape the balance of power across three continents — and almost nobody saw it coming.", visualStyle: "dossier", composition: "wide", sources: ["Reuters 2026", "FT Analysis"], imageGenerated: true },
  { sceneNumber: 2, actNumber: 1, narrationText: "The year was 2024. Behind closed doors in Tehran, a delegation sat across from envoys they had every reason to distrust — but desperation has a way of rewriting old grudges.", visualStyle: "echo", composition: "medium", sources: ["Al Jazeera 2024"], imageGenerated: true },
  { sceneNumber: 3, actNumber: 1, narrationText: "What they didn't know was that every word was being relayed in real-time to a situation room 4,000 miles away, where analysts were already calculating the cost of betrayal.", visualStyle: "schema", composition: "closeup", sources: ["Source 2026"], imageGenerated: false },
  { sceneNumber: 4, actNumber: 2, narrationText: "To understand how Iran fell into this trap, we need to rewind — not years, but decades — to a pattern that political theorists call the Thucydides Trap.", visualStyle: "dossier", composition: "wide", sources: ["Graham Allison 2017"], imageGenerated: false },
  { sceneNumber: 5, actNumber: 2, narrationText: "The concept is deceptively simple: when a rising power threatens to displace a ruling one, the resulting structural stress makes war — or catastrophic miscalculation — almost inevitable.", visualStyle: "schema", composition: "environmental", sources: [], imageGenerated: false },
  { sceneNumber: 6, actNumber: 3, narrationText: "And here's the part that should terrify every strategist watching from the sidelines: the trap doesn't require malice. It only requires momentum.", visualStyle: "dossier", composition: "closeup", sources: ["RAND Corp"], imageGenerated: false },
];

export const MOCK_STORYBOARD_SCENES: StoryboardScene[] = [
  {
    sceneNumber: 1,
    narrationText: "In the shadow of a crumbling empire, one decision would reshape the balance of power across three continents.",
    panels: Array.from({ length: 3 }, (_, i) => ({ id: `s1-p${i + 1}`, selected: i === 0 })),
    selectedPanel: 0,
  },
  {
    sceneNumber: 2,
    narrationText: "The year was 2024. Behind closed doors in Tehran, a delegation sat across from envoys they had every reason to distrust.",
    panels: Array.from({ length: 3 }, (_, i) => ({ id: `s2-p${i + 1}`, selected: false, approved: i === 1 })),
    approved: true,
    selectedPanel: 1,
  },
  {
    sceneNumber: 3,
    narrationText: "What they didn't know was that every word was being relayed in real-time to a situation room 4,000 miles away.",
    panels: Array.from({ length: 3 }, (_, i) => ({ id: `s3-p${i + 1}`, selected: false })),
  },
  {
    sceneNumber: 4,
    narrationText: "To understand how Iran fell into this trap, we need to rewind — not years, but decades.",
    panels: Array.from({ length: 3 }, (_, i) => ({ id: `s4-p${i + 1}`, selected: false })),
  },
];

export const MOCK_RENDER_STATE: RenderState = {
  progress: 67,
  resolution: "1920x1080",
  fps: 30,
  duration: "14:32",
  musicTrack: "Tension Rising - Cinematic",
  exportFormat: "MP4 (H.264)",
  ramUsage: "29x310 GB",
  cpuLoad: "3.8%",
  timeRemaining: "1h 21m",
  scenes: [
    { type: "image", label: "", color: "var(--turquoise)" },
    { type: "video", label: "Video", color: "var(--red)" },
    { type: "voice", label: "Voice", color: "var(--green)" },
    { type: "sound", label: "", color: "var(--gold)" },
    { type: "image", label: "", color: "var(--turquoise)" },
    { type: "video", label: "Video", color: "var(--red)" },
    { type: "video", label: "", color: "var(--purple)" },
    { type: "voice", label: "Voice", color: "var(--green)" },
  ],
};

export const MOCK_SETTINGS: SettingsData = {
  channelName: "Economy FastForward",
  niche: "Geopolitics",
  targetAudience: "Adults 25-45 interested in geopolitics, economics, and global power dynamics",
  visualStyle: "cinematic_illustration",
  accentColor: "turquoise",
  frameworks: [
    { name: "Thucydides Trap", enabled: true },
    { name: "Game Theory", enabled: true },
    { name: "Machiavelli", enabled: true },
    { name: "Sun Tzu", enabled: true },
    { name: "Strengthen", enabled: false },
    { name: "Rang Fraw", enabled: false },
    { name: "Social Moods", enabled: false },
    { name: "Haapiliator", enabled: false },
    { name: "Five Warms", enabled: false },
    { name: "Mochalism", enabled: false },
  ],
  integrations: [
    { name: "YouTube", icon: "youtube", connected: true },
    { name: "Slack", icon: "slack", connected: true },
    { name: "Airtable", icon: "airtable", connected: false },
    { name: "Google Drive", icon: "drive", connected: true },
  ],
};

export const MOCK_VOICE_SEGMENTS: VoiceSegment[] = [
  {
    id: "vs1",
    sceneNumber: 1,
    narrationText: "In the shadow of a crumbling empire, one decision would reshape the balance of power across three continents — and almost nobody saw it coming.",
    duration: "9s",
    panels: Array.from({ length: 9 }, (_, i) => ({ id: `vs1-p${i + 1}` })),
    selectedPanel: 4,
  },
  {
    id: "vs2",
    sceneNumber: 2,
    narrationText: "The year was 2024. Behind closed doors in Tehran, a delegation sat across from envoys they had every reason to distrust.",
    duration: "8s",
    panels: Array.from({ length: 9 }, (_, i) => ({ id: `vs2-p${i + 1}` })),
    selectedPanel: 4,
    approved: true,
  },
  {
    id: "vs3",
    sceneNumber: 3,
    narrationText: "What they didn't know was that every word was being relayed in real-time to a situation room 4,000 miles away.",
    duration: "7s",
    panels: Array.from({ length: 9 }, (_, i) => ({ id: `vs3-p${i + 1}` })),
    selectedPanel: 4,
  },
  {
    id: "vs4",
    sceneNumber: 4,
    narrationText: "To understand how Iran fell into this trap, we need to rewind — not years, but decades — to a pattern political theorists call the Thucydides Trap.",
    duration: "10s",
    panels: Array.from({ length: 9 }, (_, i) => ({ id: `vs4-p${i + 1}` })),
    selectedPanel: 4,
  },
  {
    id: "vs5",
    sceneNumber: 5,
    narrationText: "The concept is deceptively simple: when a rising power threatens to displace a ruling one, the resulting structural stress makes war almost inevitable.",
    duration: "9s",
    panels: Array.from({ length: 9 }, (_, i) => ({ id: `vs5-p${i + 1}` })),
    selectedPanel: 2,
  },
  {
    id: "vs6",
    sceneNumber: 6,
    narrationText: "And here's the part that should terrify every strategist watching from the sidelines: the trap doesn't require malice. It only requires momentum.",
    duration: "8s",
    panels: Array.from({ length: 9 }, (_, i) => ({ id: `vs6-p${i + 1}` })),
  },
];

export const MOCK_IMAGE_GEN_ITEMS: ImageGenItem[] = Array.from({ length: 12 }, (_, i) => ({
  id: `img-${i + 1}`,
  segmentId: `S-${String(Math.floor(i / 3) + 1).padStart(2, "0")}`,
  prompt: [
    "Image prompts with complete oz with holographic choices.",
    "Image prompt: Route cold and create course..",
    "Image prompts with content in with holographic and acp.",
    "Image prompt: holographic HUD-atan-contec.",
    "Images prompts with contected user....",
    "Image prompts with sony cosonies, with fenvoue ohcm...",
    "Image prompts: Holographic HUDso-lts of sceen:",
    "Image prompts: the color tops are so.",
  ][i % 8],
  progress: i < 3 ? 100 : i < 6 ? 100 : i < 9 ? Math.random() * 80 + 10 : 0,
  completed: i < 6,
}));

// Unified scene visuals — maps scenes → sentence texts → image prompts → images
export const MOCK_SCENE_VISUALS: SceneVisualGroup[] = [
  {
    sceneNumber: 1, actNumber: 1,
    narrationText: "In the shadow of a crumbling empire, one decision would reshape the balance of power across three continents — and almost nobody saw it coming.",
    visualStyle: "dossier", composition: "wide", duration: "9s",
    segments: [
      { id: "v1-s1", segmentId: "S-01", sentenceText: "In the shadow of a crumbling empire,", imagePrompt: "Aerial dusk shot of a decaying imperial palace, crumbling marble columns, deep crimson sky fading to dark navy. Dossier style, Rembrandt side-lighting, wide establishing composition.", status: "done" },
      { id: "v1-s2", segmentId: "S-02", sentenceText: "one decision would reshape the balance of power across three continents", imagePrompt: "Three-panel split screen showing continental maps — Europe, Middle East, Asia — connected by glowing red lines converging on a single point. Schema overlay, HUD grid elements, medium shot.", status: "done" },
      { id: "v1-s3", segmentId: "S-03", sentenceText: "and almost nobody saw it coming.", imagePrompt: "Close-up of a diplomat's hands clasped on a mahogany table, documents scattered, a red 'CLASSIFIED' stamp visible. Dossier style, shallow depth of field, warm amber accent.", status: "generating" },
    ],
    storyboardPanels: Array.from({ length: 9 }, (_, i) => ({ id: `sb1-p${i + 1}`, selected: i === 0 })),
  },
  {
    sceneNumber: 2, actNumber: 1,
    narrationText: "The year was 2024. Behind closed doors in Tehran, a delegation sat across from envoys they had every reason to distrust — but desperation has a way of rewriting old grudges.",
    visualStyle: "echo", composition: "medium", duration: "11s",
    segments: [
      { id: "v2-s1", segmentId: "S-04", sentenceText: "The year was 2024.", imagePrompt: "Title card style — bold '2024' in serif font overlaid on a blurred Tehran skyline at twilight. Echo painterly style, warm candlelit glow, cinematic grain.", status: "done" },
      { id: "v2-s2", segmentId: "S-05", sentenceText: "Behind closed doors in Tehran, a delegation sat across from envoys they had every reason to distrust", imagePrompt: "Interior of an ornate Persian meeting room, two groups of officials seated across a long table, tension visible in body language. Echo historical style, oil painting texture, medium shot.", status: "done" },
      { id: "v2-s3", segmentId: "S-06", sentenceText: "but desperation has a way of rewriting old grudges.", imagePrompt: "Close-up of two hands reaching across a table in a reluctant handshake, gold rings catching candlelight. Echo style, Caravaggio lighting, tight portrait crop.", status: "pending" },
    ],
    storyboardPanels: Array.from({ length: 9 }, (_, i) => ({ id: `sb2-p${i + 1}`, selected: false, approved: i === 4 })),
    storyboardApproved: true,
    selectedStoryboardPanel: 4,
  },
  {
    sceneNumber: 3, actNumber: 1,
    narrationText: "What they didn't know was that every word was being relayed in real-time to a situation room 4,000 miles away, where analysts were already calculating the cost of betrayal.",
    visualStyle: "schema", composition: "closeup", duration: "10s",
    segments: [
      { id: "v3-s1", segmentId: "S-07", sentenceText: "What they didn't know was that every word was being relayed in real-time", imagePrompt: "Glowing data streams flowing through fiber optic cables, digital signal visualization with turquoise HUD overlay. Schema style, neon accents on dark background, environmental shot.", status: "done" },
      { id: "v3-s2", segmentId: "S-08", sentenceText: "to a situation room 4,000 miles away,", imagePrompt: "Pentagon-style situation room with multiple screens showing satellite feeds, blue-lit operators at workstations. Schema HUD overlay, wide establishing shot, cold teal lighting.", status: "generating" },
      { id: "v3-s3", segmentId: "S-09", sentenceText: "where analysts were already calculating the cost of betrayal.", imagePrompt: "Close-up of a screen showing risk assessment calculations, red warning indicators, a hand pointing at key data. Schema data overlay style, close-up composition, turquoise and red accent.", status: "pending" },
    ],
  },
  {
    sceneNumber: 4, actNumber: 2,
    narrationText: "To understand how Iran fell into this trap, we need to rewind — not years, but decades — to a pattern that political theorists call the Thucydides Trap.",
    visualStyle: "dossier", composition: "wide", duration: "10s",
    segments: [
      { id: "v4-s1", segmentId: "S-10", sentenceText: "To understand how Iran fell into this trap,", imagePrompt: "A chess board with Persian-styled pieces, one king piece tipping over in slow motion, dramatic spotlight. Dossier style, Rembrandt lighting, overhead shot.", status: "pending" },
      { id: "v4-s2", segmentId: "S-11", sentenceText: "we need to rewind — not years, but decades", imagePrompt: "Time-lapse montage of Tehran skyline transforming from 1970s to present day, overlaid calendar pages peeling away. Dossier documentary style, wide pan composition.", status: "pending" },
      { id: "v4-s3", segmentId: "S-12", sentenceText: "to a pattern that political theorists call the Thucydides Trap.", imagePrompt: "Ancient Greek marble bust of Thucydides with modern geopolitical map projected onto it, glowing connection lines. Echo/Schema hybrid, medium portrait composition.", status: "pending" },
    ],
  },
];

// Pipeline stage counts for the funnel
export const PIPELINE_FUNNEL = [
  { label: "Researching", count: 1, color: "var(--turquoise)" },
  { label: "Scripting", count: 1, color: "var(--orange)" },
  { label: "Voice", count: 1, color: "var(--green)" },
  { label: "Visuals", count: 1, color: "var(--purple)" },
  { label: "Storyboard", count: 1, color: "var(--turquoise)" },
  { label: "Rendering", count: 1, color: "var(--red)" },
  { label: "Published", count: 6, color: "var(--green)" },
];
