#!/bin/bash
# StoryEngine Agent Daily Report
# Runs at 11 PM, generates a plain-English summary + opens a PR for the day's work.
# Output: storyengine/agents/reports/YYYY-MM-DD.md + GitHub PR

SCRIPT_DIR_DR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="${AGENT_PROJECT_ROOT:-${SCRIPT_DIR_DR}/../..}"
AGENTS_DIR="$PROJECT_ROOT/storyengine/agents"
REPORTS_DIR="$AGENTS_DIR/reports"
RUBRIC_URL="http://localhost:5050"
CLAUDE_BIN="${CLAUDE_BIN:-claude}"
TODAY=$(date +%Y-%m-%d)
REPORT_FILE="$REPORTS_DIR/$TODAY.md"

mkdir -p "$REPORTS_DIR"

cd "$PROJECT_ROOT"
git checkout main 2>/dev/null || true
git pull --rebase origin main 2>/dev/null || true

# Gather today's git commits
COMMITS=$(git log --since="$TODAY 00:00" --until="$TODAY 23:59" --oneline --no-merges 2>/dev/null || echo "No commits today")
COMMIT_COUNT=$(echo "$COMMITS" | grep -c "." 2>/dev/null || echo "0")

# Gather commit details
DIFF_STAT=$(git log --since="$TODAY 00:00" --until="$TODAY 23:59" --stat --no-merges 2>/dev/null | tail -1 || echo "No changes")

# Read current task queue state
TASK_QUEUE=$(cat "$AGENTS_DIR/task-queue.json" 2>/dev/null || echo "{}")

# Report status to RUBRIC
curl -s -X POST "$RUBRIC_URL/api/agent-status" \
  -H "Content-Type: application/json" \
  -d '{"agent": "orchestrator", "status": "active", "task": "Writing daily report + opening PR"}' 2>/dev/null || true

# Generate the report using Claude
$CLAUDE_BIN --print -p "$(cat <<'PROMPT'
You are writing a daily progress report for the StoryEngine agent team.
Write it in plain English for a non-technical founder who wants to know what happened today.

Keep it SHORT — under 300 words. Use simple language. No jargon.

## Today's Date
DATEPLACEHOLDER

## Git Commits Today (COUNTPLACEHOLDER total)
COMMITSPLACEHOLDER

## Files Changed Summary
DIFFPLACEHOLDER

## Current Task Queue State
QUEUEPLACEHOLDER

## Report Format

Write the report in this exact format (no other text):

# Daily Report — DATEPLACEHOLDER

## What Got Done Today
[2-5 bullet points in plain English. e.g. "Fixed a bug where image approvals weren't saving correctly" not "Standardized asset status enum case sensitivity"]

## Progress
[Which tab/page are we on? How many tasks done vs remaining? Simple fraction like "Tab 6 of 16 — 12 of 62 tasks complete"]

## What's Next Tomorrow
[2-3 bullet points of what the agents will work on next based on the pending tasks]

## Any Issues?
[Note anything that failed or got stuck. If nothing, say "All clear."]
PROMPT
" | sed "s/DATEPLACEHOLDER/$TODAY/g; s/COUNTPLACEHOLDER/$COMMIT_COUNT/g" > "$REPORT_FILE"

# Append the raw commit list to the report
echo "" >> "$REPORT_FILE"
echo "---" >> "$REPORT_FILE"
echo "## Raw Commits" >> "$REPORT_FILE"
echo '```' >> "$REPORT_FILE"
echo "$COMMITS" >> "$REPORT_FILE"
echo '```' >> "$REPORT_FILE"

# Commit the report
git add "$REPORT_FILE" 2>/dev/null || true
git add "$AGENTS_DIR/task-queue.json" 2>/dev/null || true
git commit -m "report: daily summary for $TODAY" 2>/dev/null || true
git push origin main 2>/dev/null || true

# Create or update the daily PR
EXISTING_PR=$(gh pr list --head main --state open --json number --jq '.[0].number' 2>/dev/null || echo "")

if [ -z "$EXISTING_PR" ] || [ "$EXISTING_PR" = "null" ]; then
  # Create new PR with today's report as body
  REPORT_BODY=$(cat "$REPORT_FILE")
  gh pr create \
    --base main \
    --head main \
    --title "Agent Build: $TODAY" \
    --body "$(cat <<EOF
$REPORT_BODY

---
*Auto-generated by the StoryEngine Agent Team. Review and merge when ready.*
EOF
)" 2>/dev/null && echo "PR created" || echo "PR creation failed"
else
  # Update existing PR body with latest report
  REPORT_BODY=$(cat "$REPORT_FILE")
  gh pr edit "$EXISTING_PR" \
    --title "Agent Build: $TODAY" \
    --body "$(cat <<EOF
$REPORT_BODY

---
*Auto-generated by the StoryEngine Agent Team. Review and merge when ready.*
EOF
)" 2>/dev/null && echo "PR #$EXISTING_PR updated" || echo "PR update failed"
  echo "Existing PR: #$EXISTING_PR"
fi

# ─── Push to Telegram ──────────────────────────────────────────────────────
source "$AGENTS_DIR/notify-telegram.sh" 2>/dev/null || true

# Get latest launch score from activity log
RUBRIC_DATA="$PROJECT_ROOT/rubric/scaffold/data"
LAUNCH_SCORE=$(python3 -c "
import json
try:
    logs = json.load(open('$RUBRIC_DATA/activity-log.json'))
    scores = [e for e in logs[:100] if e.get('task') == 'launch-readiness']
    if scores:
        print(scores[0].get('summary', 'No score yet'))
    else:
        print('No launch score yet')
except: print('No launch score yet')
" 2>/dev/null || echo "No launch score yet")

# Send Telegram summary (first 500 chars of report + launch score)
if [ -f "$REPORT_FILE" ]; then
  TELEGRAM_SUMMARY=$(head -20 "$REPORT_FILE" | sed 's/#//g' | head -c 500)
  notify_telegram "*Daily Report — $TODAY*

$TELEGRAM_SUMMARY

*Launch Readiness:* $LAUNCH_SCORE

_Full report in PR on GitHub_"
fi

# Report idle status
curl -s -X POST "$RUBRIC_URL/api/agent-status" \
  -H "Content-Type: application/json" \
  -d "{\"agent\": \"orchestrator\", \"status\": \"idle\", \"task\": \"Daily report + PR done: $TODAY\"}" 2>/dev/null || true

echo "Report saved to: $REPORT_FILE"
